export interface Indicator {
  indicatorCode: string;
  indicatorName: string;
  indicatorDescription: string;
  indicatorGroup: 'medicare' | 'rates' | 'commercial' | 'general';
  aggregation: string;
  selected: boolean;
  format: string;
  pScale: number;
  pSymbol: string;
}

export const INDICATORS: Indicator[] =
  [
    { indicatorCode: "rate", indicatorName: "Rates", indicatorDescription: "Rate", indicatorGroup: "rates", aggregation: "q50", selected: false, pScale: 0, pSymbol: "", format: "0.00" },

    { indicatorCode: "medicaid_enrolled_lbas", indicatorName: "Geographic Distribution of  LBAs", indicatorDescription: "Medicaid Enrolled LBAs", indicatorGroup: "medicare", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "medicaid_pop_total", indicatorName: "Medicaid Enrolled Children with Autism", indicatorDescription: "Geographic Distribution of LBA.", indicatorGroup: "medicare", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },

    { indicatorCode: "cnt_payers", indicatorName: "Payers count by county", indicatorDescription: "Payers count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "cnt_networks", indicatorName: "Neworks count by county", indicatorDescription: "Networks count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "cnt_ein", indicatorName: "Ein count by county", indicatorDescription: "Ein count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    // { indicatorCode: "cnt_entities", indicatorName: "Entities count by county", indicatorDescription: "Entities count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "bcba_d", indicatorName: "bcba_d count by county", indicatorDescription: "bcba_d count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "bcba", indicatorName: "bcba count by county", indicatorDescription: "bcba count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "bcaba", indicatorName: "bcaba count by county", indicatorDescription: "bcaba count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "rbt", indicatorName: "rbt count by county", indicatorDescription: "rbt count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },

    { indicatorCode: "population", indicatorName: "population", indicatorDescription: "population", indicatorGroup: "general", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "area", indicatorName: "Area (km2)", indicatorDescription: "Area of land in km2.", indicatorGroup: "general", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "pop_density", indicatorName: "Population Density", indicatorDescription: "Number of inhabitants per km2.", indicatorGroup: "general", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0.0" },
  ]

// List of codes
export const CODES = [
  { id: '00000', name: 'All' },
  { id: '97151', name: '97151' },
  { id: '97152', name: '97152' },
  { id: '97153', name: '97153' },
  { id: '97154', name: '97154' },
  { id: '97155', name: '97155' },
  { id: '97156', name: '97156' },
  { id: '97157', name: '97157' },
  { id: '97158', name: '97158' },
];

export const TAXONOMY = [
  { id: 'ZZ', name: 'ALL' },
  // { id: '101Y00000X', name: 'Counselor' },
  // { id: '101YM0800X', name: 'Mental Health Counselor' },
  // { id: '101YP2500X', name: 'Professional Counselor' },
  { id: '103K00000X', name: 'Behavioral Analyst (BCBA)' },
  // { id: '103T00000X', name: 'Psychologist' },
  // { id: '103TB0200X', name: 'Cognitive & Behavioral Psychologist' },
  // { id: '103TC0700X', name: 'Clinical Psychologist' },
  // { id: '103TC1900X', name: 'Counseling Psychologist' },
  // { id: '103TC2200X', name: 'Clinical Child & Adolescent Psychologist' },
  // { id: '103TM1800X', name: 'Intellectual & Developmental Disabilities Psychologist' },
  // { id: '1041C0700X', name: 'Clinical Social Worker' },
  { id: '106E00000X', name: 'Assistant Behavior Analyst' }, // New
  // { id: '106H00000X', name: 'Marriage & Family Therapist' },
  { id: '106S00000X', name: 'Behavior Technician (BT)' },
  // { id: '152W00000X', name: 'Optometrist' },
  // { id: '156F00000X', name: 'Technician/Technologist' },
  // { id: '171M00000X', name: 'Case Manager/Care Coordinator' },
  // { id: '172V00000X', name: 'Community Health Worker' },
  // { id: '174400000X', name: 'Specialist' },
  // { id: '207W00000X', name: 'Ophthalmology Physician' },
  // { id: '2080P0006X', name: 'Developmental - Behavioral Pediatrics Physician' },
  // { id: '2081S0010X', name: 'Sports Medicine (Physical Medicine & Rehabilitation) Physician' },
  // { id: '2084N0402X', name: 'Neurology with Special Qualifications in Child Neurology Physician' },
  // { id: '2084P0800X', name: 'Psychiatry Physician' },
  // { id: '2084P0804X', name: 'Child & Adolescent Psychiatry Physician' },
  // { id: '222Q00000X', name: 'Developmental Therapist' },
  // { id: '225100000X', name: 'Physical Therapist' },
  // { id: '2251P0200X', name: 'Pediatric Physical Therapist' },
  // { id: '225500000X', name: 'Respiratory/Developmental/Rehabilitative Specialist/Technologist' },
  // { id: '225X00000X', name: 'Occupational Therapist' },
  // { id: '225XP0200X', name: 'Pediatric Occupational Therapist' },
  // { id: '235Z00000X', name: 'Speech-Language Pathologist' },
  // { id: '247200000X', name: 'Other Technician' },
  // { id: '2472E0500X', name: 'EEG Technician' },
  // { id: '251300000X', name: 'Local Education Agency (LEA)' },
  // { id: '251C00000X', name: 'Developmentally Disabled Services Day Training Agency' },
  // { id: '251E00000X', name: 'Home Health Agency' },
  // { id: '251K00000X', name: 'Public Health or Welfare Agency' },
  // { id: '251S00000X', name: 'Community/Behavioral Health Agency' },
  // { id: '252Y00000X', name: 'Early Intervention Provider Agency' },
  // { id: '261Q00000X', name: 'Clinic/Center' },
  // { id: '261QD1600X', name: 'Developmental Disabilities Clinic/Center' },
  // { id: '261QH0700X', name: 'Hearing and Speech Clinic/Center' },
  // { id: '261QM0801X', name: 'Mental Health Clinic/Center (Including Community Mental Health Center)' },
  // { id: '261QM0855X', name: 'Adolescent and Children Mental Health Clinic/Center' },
  // { id: '261QM1300X', name: 'Multi-Specialty Clinic/Center' },
  // { id: '261QP2000X', name: 'Physical Therapy Clinic/Center' },
  // { id: '261QR0400X', name: 'Rehabilitation Clinic/Center' },
  // { id: '281P00000X', name: 'Chronic Disease Hospital' },
  // { id: '281PC2000X', name: 'Children\'s Chronic Disease Hospital' },
  // { id: '282E00000X', name: 'Long Term Care Hospital' },
  // { id: '282J00000X', name: 'Religious Nonmedical Health Care Institution' },
  // { id: '282N00000X', name: 'General Acute Care Hospital' },
  // { id: '282NC0060X', name: 'Critical Access Hospital' },
  // { id: '282NC2000X', name: 'Children\'s Hospital' },
  // { id: '282NR1301X', name: 'Rural Acute Care Hospital' },
  // { id: '282NW0100X', name: 'Women\'s Hospital' },
  // { id: '283Q00000X', name: 'Psychiatric Hospital' },
  // { id: '283X00000X', name: 'Rehabilitation Hospital' },
  // { id: '283XC2000X', name: 'Children\'s Rehabilitation Hospital' },
  // { id: '284300000X', name: 'Special Hospital' },
  // { id: '286500000X', name: 'Military Hospital' },
  // { id: '2865M2000X', name: 'Military General Acute Care Hospital' },
  // { id: '302F00000X', name: 'Exclusive Provider Organization' },
  // { id: '373H00000X', name: 'Day Training/Habilitation Specialist' },
  // { id: '374700000X', name: 'Technician' },
  // { id: '385HR2060X', name: 'Child Intellectual and/or Developmental Disabilities Respite Care' }
]

/*
SELECT CONCAT('{id: \'ZZ\', name: \'ALL\', pId: \'ZZ\'},') j
UNION ALL
SELECT j FROM (
SELECT DISTINCT
    n.name
    , CONCAT('{id: \'', n.t_id36, '\', name: \'', n.name, ' (', n.region, ')', '\', pId: \'', p.p_id36, '\'},') j
FROM bcba.serifhealth_network n
INNER JOIN bcba.serifhealth_payer p ON p.id = n.payer_id
ORDER BY n.name
) d;
 */
export const PAYERS = [
  { id: 'ZZ', name: 'ALL' },
  { id: '37', name: 'Aetna' },
  { id: '2G', name: 'Alliant Health Plans' },
  { id: '3C', name: 'Allina Health' },
  { id: '24', name: 'AllWays Health Partners' },
  { id: '28', name: 'Ambetter' },
  { id: '2R', name: 'Americas PPO' },
  { id: '4E', name: 'Amerihealth Caritas Next' },
  { id: '3U', name: 'AmeriHealth Insurance Company of New Jersey' },
  { id: '3A', name: 'Anthem' },
  { id: '0M', name: 'Arkansas Blue Cross and Blue Shield' },
  { id: '4H', name: 'Aspirus Health Plan' },
  { id: '48', name: 'Asuris Northwest Health' },
  { id: '0T', name: 'AultCare Insurance Company' },
  { id: '4V', name: 'Avera Health Plans Inc' },
  { id: '4Q', name: 'AvMed' },
  { id: '25', name: 'Baylor Scott and White Health Plan' },
  { id: '1C', name: 'BCBS Puerto Rico (Triple S)' },
  { id: '38', name: 'Beacon Health Options' },
  { id: '3V', name: 'Blue Card' },
  { id: '0R', name: 'Blue Cross and Blue Shield of Illinois' },
  { id: '2D', name: 'Blue Cross and Blue Shield of Kansas' },
  { id: '1G', name: 'Blue Cross and Blue Shield of Kansas City' },
  { id: '1N', name: 'Blue Cross and Blue Shield of Montana' },
  { id: '2U', name: 'Blue Cross and Blue Shield of Nebraska' },
  { id: '01', name: 'Blue Cross and Blue Shield of New Mexico' },
  { id: '3I', name: 'Blue Cross and Blue Shield of North Carolina' },
  { id: '2K', name: 'Blue Cross and Blue Shield of Oklahoma' },
  { id: '3S', name: 'Blue Cross and Blue Shield of Texas' },
  { id: '0F', name: 'Blue Cross and Blue Shield of Vermont' },
  { id: '2V', name: 'Blue Cross and Blue Shield of Wyoming' },
  { id: '3W', name: 'Blue Cross Blue Shield Louisiana' },
  { id: '44', name: 'Blue Cross Blue Shield of Alabama' },
  { id: '3B', name: 'Blue Cross Blue Shield of Arizona' },
  { id: '2C', name: 'Blue Cross Blue Shield of Massachusetts' },
  { id: '0B', name: 'Blue Cross Blue Shield of Michigan' },
  { id: '43', name: 'Blue Cross Blue Shield of Minnesota' },
  { id: '16', name: 'Blue Cross Blue Shield of Mississippi' },
  { id: '20', name: 'Blue Cross Blue Shield of North Dakota' },
  { id: '1T', name: 'Blue Cross Blue Shield of Rhode Island' },
  { id: '3T', name: 'Blue Cross of Idaho' },
  { id: '1Q', name: 'Blue Shield of California' },
  { id: '3M', name: 'BlueCross BlueShield of South Carolina' },
  { id: '1L', name: 'BlueCross BlueShield of Tennessee' },
  { id: '3D', name: 'BridgeSpan' },
  { id: '31', name: 'Capital BlueCross' },
  { id: '2W', name: 'Capital District Physicians Health Plan' },
  { id: '4J', name: 'Capital Health Plan Inc' },
  { id: '0W', name: 'CareFirst BlueCross BlueShield' },
  { id: '4A', name: 'Caresource' },
  { id: '4P', name: 'Centivo' },
  { id: '1J', name: 'Christus' },
  { id: '1W', name: 'Cigna Corporation' },
  { id: '1V', name: 'Common Ground Healthcare Cooperative' },
  { id: '2O', name: 'Community Health Choice' },
  { id: '3X', name: 'Community Health Options' },
  { id: '1H', name: 'CommunityCare' },
  { id: '2H', name: 'ComPsych' },
  { id: '2E', name: 'Coventry Health Plan of Florida' },
  { id: '3K', name: 'Cox Health Systems' },
  { id: '17', name: 'Curative' },
  { id: '0J', name: 'DakotaCare' },
  { id: '1O', name: 'Dean Health Plan' },
  { id: '40', name: 'Denver Health Medical Plan' },
  { id: '1I', name: 'EHN' },
  { id: '4O', name: 'Emblem Health' },
  { id: '2N', name: 'EMI Health' },
  { id: '32', name: 'Encore' },
  { id: '0S', name: 'Excellus BlueCross BlueShield' },
  { id: '33', name: 'Fallon Health' },
  { id: '0A', name: 'Fidelis Care' },
  { id: '0G', name: 'First Health' },
  { id: '2S', name: 'Florida Blue' },
  { id: '2M', name: 'Geisinger Health Plan' },
  { id: '1E', name: 'Group Health Cooperative of South Central Wisconsin' },
  { id: '0Z', name: 'HAP' },
  { id: '06', name: 'Harvard Pilgrim Healthcare' },
  { id: '14', name: 'Hawaii Medical Assurance Association' },
  { id: '2L', name: 'Hawaii Medical Service Association' },
  { id: '0V', name: 'Health Advantage HMO Partners' },
  { id: '1S', name: 'Health Alliance' },
  { id: '10', name: 'Health Net' },
  { id: '0K', name: 'Health New England Inc' },
  { id: '4L', name: 'Health Payment Systems' },
  { id: '4U', name: 'Health Plan of Nevada' },
  { id: '47', name: 'Health2Business' },
  { id: '08', name: 'Healthcare Highways' },
  { id: '4I', name: 'Healthfirst' },
  { id: '49', name: 'HealthPartners' },
  { id: '0L', name: 'HealthPlan Services' },
  { id: '2Y', name: 'Healthsmart' },
  { id: '2Z', name: 'Henry Ford Health System' },
  { id: '36', name: 'Highmark Blue Cross Blue Shield Delaware' },
  { id: '1Y', name: 'Highmark Blue Cross Blue Shield Pennsylvania' },
  { id: '4C', name: 'Highmark Blue Cross Blue Shield West Virginia' },
  { id: '3Q', name: 'Highmark Blue Cross Blue Shield Western New York' },
  { id: '13', name: 'Highmark Blue Shield of Northeastern New York' },
  { id: '1Z', name: 'Highmark Blue Shield Pennsylvania' },
  { id: '21', name: 'HMA' },
  { id: '4G', name: 'Hometown Health Plan' },
  { id: '41', name: 'Horizon Blue Cross Blue Shield of New Jersey' },
  { id: '0Q', name: 'Humana' },
  { id: '1A', name: 'Imagine360' },
  { id: '12', name: 'Independence BCBS' },
  { id: '02', name: 'Independent Health' },
  { id: '4R', name: 'Innovation Health Plan' },
  { id: '09', name: 'Kaiser Foundation Health Plan' },
  { id: '2X', name: 'Lifewise' },
  { id: '1D', name: 'Magellan Health' },
  { id: '1X', name: 'MagnaCare' },
  { id: '35', name: 'McLaren' },
  { id: '0U', name: 'Medcost' },
  { id: '1F', name: 'Medica' },
  { id: '3E', name: 'Medical Mutual of Ohio' },
  { id: '19', name: 'MercyCare' },
  { id: '1K', name: 'Meritain Health' },
  { id: '3J', name: 'MHN' },
  { id: '2B', name: 'Midlands Choice' },
  { id: '18', name: 'Moda Health' },
  { id: '07', name: 'Molina Healthcare' },
  { id: '3F', name: 'MultiPlan' },
  { id: '2I', name: 'MVP Health Care' },
  { id: '0E', name: 'Neighborhood Health Plan of Rhode Island' },
  { id: '3P', name: 'Network Health' },
  { id: '3Y', name: 'Ohio PPO Connect' },
  { id: '3Z', name: 'Optima Health' },
  { id: '26', name: 'Optum' },
  { id: '1U', name: 'Oscar Insurance Corporation' },
  { id: '34', name: 'Oxford Health Plan' },
  { id: '4F', name: 'Pacificare' },
  { id: '3R', name: 'PacificSource Health Plans' },
  { id: '04', name: 'Paramount Insurance Company' },
  { id: '2T', name: 'Physicians Health Plan' },
  { id: '4S', name: 'Physicians Health Plan of Northern Indiana' },
  { id: '4M', name: 'Piedmont Health Plan' },
  { id: '2P', name: 'Point32Health' },
  { id: '0P', name: 'Preferred One' },
  { id: '4T', name: 'Premera Blue Cross' },
  { id: '42', name: 'Presbyterian Health Plan' },
  { id: '3O', name: 'Prime Health Services' },
  { id: '1M', name: 'Priority Health' },
  { id: '3H', name: 'Prominence Health Plan' },
  { id: '3L', name: 'ProviDRs Care' },
  { id: '11', name: 'Qualchoice' },
  { id: '4N', name: 'Quartz' },
  { id: '4W', name: 'Regence BlueCross BlueShield of Oregon' },
  { id: '30', name: 'Regence BlueCross BlueShield of Utah' },
  { id: '29', name: 'Regence BlueShield of Idaho' },
  { id: '4D', name: 'Regence BlueShield of Washington' },
  { id: '2Q', name: 'Rocky Mountain Health Plan' },
  { id: '39', name: 'Sagamore Health Network' },
  { id: '0D', name: 'Sana Benefits' },
  { id: '2J', name: 'Sanford Health Group' },
  { id: '1P', name: 'Security Health Plan of Wisconsin' },
  { id: '15', name: 'SelectHealth' },
  { id: '22', name: 'SIHO Insurance Services' },
  { id: '1B', name: 'Summa Care' },
  { id: '0X', name: 'Sutter Health Plus' },
  { id: '0O', name: 'Texas Health Aetna' },
  { id: '3N', name: 'The Alliance' },
  { id: '0H', name: 'The Health Plan' },
  { id: '05', name: 'Trilogy' },
  { id: '23', name: 'Truli' },
  { id: '0I', name: 'Tufts Health Plan' },
  { id: '0C', name: 'UCare' },
  { id: '0Y', name: 'UHA' },
  { id: '2F', name: 'UnitedHealthcare' },
  { id: '46', name: 'Univera Healthcare' },
  { id: '45', name: 'University of Utah Health Plans' },
  { id: '3G', name: 'UPMC Health Plan' },
  { id: '4K', name: 'Valley Health Plan' },
  { id: '4B', name: 'Wellmark Blue Cross and Blue Shield of Iowa' },
  { id: '27', name: 'Wellmark Blue Cross and Blue Shield of South Dakota' },
  { id: '1R', name: 'WellSense Health Plan' },
  { id: '2A', name: 'Western Health Advantage' },
  { id: '03', name: 'WPS Health Plan' },
  { id: '0N', name: 'Yale University Health Plan' },

];


/*
SELECT CONCAT('{id: \'ZZ\', name: \'ALL\', pId: \'ZZ\'},') j
UNION ALL
SELECT j FROM (
SELECT DISTINCT
  n.name,
    CONCAT('{id: \'', n.t_id36, '\', name: \'', n.name, ' (', n.region, ')', '\', pId: \'', p.p_id36, '\'},') j
FROM bcba.serifhealth_network n
INNER JOIN bcba.serifhealth_payer p ON p.id = n.payer_id
ORDER BY n.name
) d;
*/
export const NETWORKS = [
  { id: 'ZZ', name: 'ALL', pId: 'ZZ' },
  { id: 'DH', name: '1199SEIU Open Access Aetna Select (USA)', pId: '37' },
  { id: 'DI', name: '32BJ POS (NY)', pId: '3A' },
  { id: '67', name: '3M (USA)', pId: '2B' },
  { id: '96', name: 'Achieve (MN)', pId: '49' },
  { id: 'A6', name: 'ACTBLIZPP (USA)', pId: '4P' },
  { id: '3J', name: 'Advantage HMO (CA)', pId: '2A' },
  { id: 'CP', name: 'Aetna CVS Exchange California (CA)', pId: '37' },
  { id: '2Q', name: 'Aetna CVS Exchange Delaware (DE)', pId: '37' },
  { id: '6K', name: 'Aetna CVS Exchange Florida (FL)', pId: '37' },
  { id: '06', name: 'Aetna CVS Exchange Georgia (GA)', pId: '37' },
  { id: '6Q', name: 'Aetna CVS Exchange Illinois (IL)', pId: '37' },
  { id: '3F', name: 'Aetna CVS Exchange Indiana (IN)', pId: '37' },
  { id: '0Y', name: 'Aetna CVS Exchange Kansas (KS)', pId: '37' },
  { id: '8T', name: 'Aetna CVS Exchange Maryland (MD)', pId: '37' },
  { id: 'AS', name: 'Aetna CVS Exchange Missouri (MO)', pId: '37' },
  { id: '8A', name: 'Aetna CVS Exchange Nevada (NV)', pId: '37' },
  { id: '54', name: 'Aetna CVS Exchange New Jersey (NJ)', pId: '37' },
  { id: '73', name: 'Aetna CVS Exchange North Carolina (NC)', pId: '37' },
  { id: '3V', name: 'Aetna CVS Exchange Ohio (OH)', pId: '37' },
  { id: '0Q', name: 'Aetna CVS Exchange Texas (TX)', pId: '37' },
  { id: 'C4', name: 'Aetna CVS Exchange Utah (UT)', pId: '37' },
  { id: '7Q', name: 'Aetna CVS Exchange Virginia (VA)', pId: '37' },
  { id: '48', name: 'Aetna EPO (USA)', pId: '37' },
  { id: '4Y', name: 'Aetna Gold (CA)', pId: '37' },
  { id: '58', name: 'Aetna HMO (GA)', pId: '37' },
  { id: '6R', name: 'Aetna HMO (FL)', pId: '37' },
  { id: 'D3', name: 'Aetna HMO (LA)', pId: '37' },
  { id: '6Y', name: 'Aetna HMO (IA)', pId: '37' },
  { id: '7H', name: 'Aetna HMO (TX)', pId: '37' },
  { id: '5P', name: 'Aetna HMO (NJ)', pId: '37' },
  { id: '27', name: 'Aetna HMO (ME)', pId: '37' },
  { id: 'BT', name: 'Aetna National Gold HMO (USA)', pId: '37' },
  { id: '89', name: 'Aetna PPO (TX)', pId: '0O' },
  { id: '10', name: 'Aetna PPO (USA)', pId: '37' },
  { id: '4D', name: 'AHP (SD)', pId: '4V' },
  { id: '1G', name: 'AK Heritage (AK)', pId: '4T' },
  { id: '6J', name: 'Alabama Exchange Plan (AL)', pId: '2F' },
  { id: 'BK', name: 'All Files (MO)', pId: '3K' },
  { id: 'D6', name: 'All Minnesota (MN)', pId: '43' },
  { id: '91', name: 'All MMO (OH)', pId: '3E' },
  { id: '3I', name: 'Alliance Comprehensive (WI)', pId: '3N' },
  { id: '7I', name: 'Alliance Premier (WI)', pId: '3N' },
  { id: '83', name: 'Alliance Select PPO (IA)', pId: '4B' },
  { id: '35', name: 'Allies HMO (MA)', pId: '24' },
  { id: '53', name: 'Allina Health Aetna (MN)', pId: '3C' },
  { id: '9E', name: 'Ambetter Exchange AL (AL)', pId: '28' },
  { id: '8K', name: 'Ambetter Exchange AR (AR)', pId: '28' },
  { id: '1U', name: 'Ambetter Exchange AZ (AZ)', pId: '28' },
  { id: 'D4', name: 'Ambetter Exchange CA (CA)', pId: '28' },
  { id: '7C', name: 'Ambetter Exchange DE (DE)', pId: '28' },
  { id: '9G', name: 'Ambetter Exchange FL (FL)', pId: '28' },
  { id: 'C0', name: 'Ambetter Exchange GA (GA)', pId: '28' },
  { id: 'DA', name: 'Ambetter Exchange IA (IA)', pId: '28' },
  { id: '5W', name: 'Ambetter Exchange IL (IL)', pId: '28' },
  { id: 'BZ', name: 'Ambetter Exchange IN (IN)', pId: '28' },
  { id: '44', name: 'Ambetter Exchange KS (KS)', pId: '28' },
  { id: '6C', name: 'Ambetter Exchange KY (KY)', pId: '28' },
  { id: '3S', name: 'Ambetter Exchange LA (LA)', pId: '28' },
  { id: '37', name: 'Ambetter Exchange MI (MI)', pId: '28' },
  { id: '4V', name: 'Ambetter Exchange MO (MO)', pId: '28' },
  { id: '6B', name: 'Ambetter Exchange MS (MS)', pId: '28' },
  { id: '6Z', name: 'Ambetter Exchange NC (NC)', pId: '28' },
  { id: '4C', name: 'Ambetter Exchange NE (NE)', pId: '28' },
  { id: 'AV', name: 'Ambetter Exchange NH (NH)', pId: '28' },
  { id: '3T', name: 'Ambetter Exchange NJ (NJ)', pId: '28' },
  { id: '4F', name: 'Ambetter Exchange NM (NM)', pId: '28' },
  { id: 'C9', name: 'Ambetter Exchange NV (NV)', pId: '28' },
  { id: '14', name: 'Ambetter Exchange OH (OH)', pId: '28' },
  { id: 'D0', name: 'Ambetter Exchange OK (OK)', pId: '28' },
  { id: '1M', name: 'Ambetter Exchange PA (PA)', pId: '28' },
  { id: 'D2', name: 'Ambetter Exchange SC (SC)', pId: '28' },
  { id: '19', name: 'Ambetter Exchange TN (TN)', pId: '28' },
  { id: '4R', name: 'Ambetter Exchange TX (TX)', pId: '28' },
  { id: '4K', name: 'Ambetter Exchange WA (WA)', pId: '28' },
  { id: 'AC', name: 'Americas PPO (USA)', pId: '2R' },
  { id: '5H', name: 'AmeriHealth Bronze - Limited (FL)', pId: '4E' },
  { id: 'CG', name: 'AmeriHealth Bronze - Limited (DE)', pId: '4E' },
  { id: 'AB', name: 'AmeriHealth Bronze -- Limited (NC)', pId: '4E' },
  { id: '40', name: 'Arizona Connect (AZ)', pId: '1W' },
  { id: '7X', name: 'Arizona Exchange Plan (AZ)', pId: '2F' },
  { id: '8S', name: 'ASA (USA)', pId: '37' },
  { id: '1Q', name: 'AvMed Entrust Gold 125-ON22 (FL)', pId: '4Q' },
  { id: '46', name: 'Aware (MN)', pId: '43' },
  { id: '52', name: 'Beacon Health Options (USA)', pId: '38' },
  { id: '9A', name: 'Blue Advantage HMO (NM)', pId: '01' },
  { id: '3Y', name: 'Blue Advantage HMO (IL)', pId: '0R' },
  { id: '57', name: 'Blue Advantage HMO (TX)', pId: '3S' },
  { id: '39', name: 'Blue Advantage PPO (OK)', pId: '2K' },
  { id: 'B9', name: 'Blue Care Elect (MA)', pId: '2C' },
  { id: '87', name: 'Blue Choice Platinum for Business (AL)', pId: '44' },
  { id: 'D1', name: 'Blue Choice PPO (TX)', pId: '3S' },
  { id: 'AY', name: 'Blue Choice PPO (OK)', pId: '2K' },
  { id: 'D5', name: 'Blue Choice Primecare (ND)', pId: '20' },
  { id: '0S', name: 'Blue Community HMO (NM)', pId: '01' },
  { id: '1I', name: 'Blue Essentials (TX)', pId: '3S' },
  { id: '6V', name: 'Blue Essentials (SC)', pId: '3M' },
  { id: '4N', name: 'Blue Focus POS (MT)', pId: '1N' },
  { id: '7K', name: 'Blue HPN Atrium (NC)', pId: '3I' },
  { id: 'BP', name: 'Blue Lincs HMO (OK)', pId: '2K' },
  { id: '4X', name: 'Blue Options PPO (OK)', pId: '2K' },
  { id: 'AZ', name: 'Blue Options PPO (SC)', pId: '3M' },
  { id: '4J', name: 'Blue Options PPO (UT)', pId: '30' },
  { id: '79', name: 'Blue Options PPO (IL)', pId: '0R' },
  { id: '3W', name: 'Blue Options PPO (FL)', pId: '2S' },
  { id: 'B0', name: 'Blue Options PPO (MT)', pId: '1N' },
  { id: '32', name: 'Blue POS (LA)', pId: '3W' },
  { id: '8B', name: 'Blue Preferred Plus (NM)', pId: '01' },
  { id: '3H', name: 'Blue Preferred PPO (NM)', pId: '01' },
  { id: 'B8', name: 'Blue Preferred PPO (OK)', pId: '2K' },
  { id: '5K', name: 'Blue Premier (TX)', pId: '3S' },
  { id: '7N', name: 'Blue Saver (LA)', pId: '3W' },
  { id: 'A8', name: 'Blue Select PPO (SD)', pId: '27' },
  { id: 'BJ', name: 'Blue Traditional PAR (OK)', pId: '2K' },
  { id: '03', name: 'Blue Value Network (ID)', pId: '3T' },
  { id: '8D', name: 'Blue Value Network (NC)', pId: '3I' },
  { id: '82', name: 'Bluecare (FL)', pId: '2S' },
  { id: '76', name: 'BlueChoice (FL)', pId: '2S' },
  { id: '1R', name: 'BMC HealthNet Silver (MA)', pId: '1R' },
  { id: '1F', name: 'Bronze (TX)', pId: '2O' },
  { id: '61', name: 'Capital Blue Cross (PA)', pId: '31' },
  { id: 'BW', name: 'Care Gold (NY)', pId: '0A' },
  { id: 'BN', name: 'Caresource Marketplace GA (GA)', pId: '4A' },
  { id: '3B', name: 'Caresource Marketplace IN (IN)', pId: '4A' },
  { id: '7O', name: 'Caresource Marketplace KY (KY)', pId: '4A' },
  { id: '9U', name: 'Caresource Marketplace NC (NC)', pId: '4A' },
  { id: '5Q', name: 'Caresource Marketplace OH (OH)', pId: '4A' },
  { id: '3Z', name: 'Caresource Marketplace WV (WV)', pId: '4A' },
  { id: '62', name: 'CDPHP (NY)', pId: '2W' },
  { id: '2X', name: 'Centercare POS (WI)', pId: '1P' },
  { id: '8O', name: 'CGHC (WI)', pId: '1V' },
  { id: 'AT', name: 'Charter Balanced (USA)', pId: '2F' },
  { id: '4T', name: 'CHO (ME)', pId: '3X' },
  { id: '0C', name: 'Choice Plus (USA)', pId: '2F' },
  { id: '38', name: 'ChoiceNet HMO (MA)', pId: '06' },
  { id: 'BE', name: 'CHP (LA)', pId: '1J' },
  { id: '4L', name: 'CHP (TX)', pId: '1J' },
  { id: '88', name: 'Cigna Pathwell PPO (USA)', pId: '1W' },
  { id: 'CN', name: 'Colorado Connect (CO)', pId: '1W' },
  { id: '9R', name: 'Colorado Doctors Plan (CO)', pId: '2Q' },
  { id: '04', name: 'Colorado Exchange Plan (CO)', pId: '2Q' },
  { id: '7Z', name: 'Commercial Fully Funded (MA)', pId: '0K' },
  { id: '6D', name: 'Commercial HMO (NV)', pId: '4U' },
  { id: '5F', name: 'Commercial HMO (MA)', pId: '24' },
  { id: 'B2', name: 'Commercial PPO (FL)', pId: '4J' },
  { id: '6E', name: 'Commercial PPO (NJ)', pId: '3U' },
  { id: '66', name: 'Commercial PPO (MA)', pId: '24' },
  { id: '9V', name: 'Community Care (OK)', pId: '1H' },
  { id: 'DF', name: 'Compass (NY)', pId: '2F' },
  { id: '95', name: 'ComPsych (USA)', pId: '2H' },
  { id: '0P', name: 'Confident Care Gold 1 (OH)', pId: '07' },
  { id: 'BH', name: 'Confident Care Gold 8 (ID)', pId: '07' },
  { id: '12', name: 'Confident Care Gold 8 (FL)', pId: '07' },
  { id: '9F', name: 'Confident Care Gold 8 (MS)', pId: '07' },
  { id: '15', name: 'Confident Care Gold 8 (KY)', pId: '07' },
  { id: '2L', name: 'Confident Care Gold 8 (IL)', pId: '07' },
  { id: '3K', name: 'Confident Care Gold 8 (MI)', pId: '07' },
  { id: 'CA', name: 'Connecticare (CT)', pId: '4O' },
  { id: '2M', name: 'ConnectorCare Health New England (MA)', pId: '0K' },
  { id: 'CZ', name: 'Connexus (OR)', pId: '18' },
  { id: '56', name: 'Constant Care Gold 8 (SC)', pId: '07' },
  { id: 'B1', name: 'Constant Care Gold 8 (WA)', pId: '07' },
  { id: '28', name: 'Constant Care Gold 8 (WI)', pId: '07' },
  { id: '9L', name: 'Constant Care Gold 8 (UT)', pId: '07' },
  { id: '8X', name: 'Constant Care Silver (NM)', pId: '07' },
  { id: '8Q', name: 'Core (USA)', pId: '2F' },
  { id: 'AK', name: 'Cornerstone (MN)', pId: '49' },
  { id: '1O', name: 'Coventry Aetna CVS Silver (FL)', pId: '2E' },
  { id: 'D7', name: 'CoveredCalifornia Platinum AIAN (CA)', pId: '4K' },
  { id: 'AP', name: 'Curative PPO (TX)', pId: '17' },
  { id: 'A5', name: 'Custom (CT)', pId: '0N' },
  { id: '6G', name: 'DakotaCare Administrative Services (SD)', pId: '0J' },
  { id: '8W', name: 'Dart Container of Michigan (USA)', pId: '3V' },
  { id: '3O', name: 'Dean Health Plan Commercial PPO (WI)', pId: '1O' },
  { id: 'CX', name: 'Direct Nonsubsidized Group (MA)', pId: '0I' },
  { id: '86', name: 'Direct Nonsubsidized Individual (MA)', pId: '0I' },
  { id: '2B', name: 'Direct Subsidized Individual (MA)', pId: '0I' },
  { id: '3L', name: 'Doctors Plan (USA)', pId: '2F' },
  { id: '50', name: 'EHN (USA)', pId: '1I' },
  { id: 'BR', name: 'Encore Combined (IN)', pId: '32' },
  { id: '8F', name: 'Endeavor Providence (OR)', pId: '18' },
  { id: '8R', name: 'Endeavor Select (OR)', pId: '18' },
  { id: '0Z', name: 'EPO (NJ)', pId: '41' },
  { id: 'AI', name: 'EPO (WI)', pId: '19' },
  { id: '0G', name: 'EPO PPO (NY)', pId: '2I' },
  { id: '1C', name: 'Essentia Choice Care (MN)', pId: '1F' },
  { id: 'BO', name: 'Essential (NY)', pId: '0A' },
  { id: '75', name: 'Essential Plan (NY)', pId: '46' },
  { id: '29', name: 'Excellus BCBS HMO (NY)', pId: '0S' },
  { id: '51', name: 'FH Umbrella (USA)', pId: '0G' },
  { id: '5J', name: 'Florida Connect (FL)', pId: '1W' },
  { id: '1X', name: 'Florida Exchange Plan (FL)', pId: '2F' },
  { id: '2U', name: 'Focus Network - MA HMO (MA)', pId: '06' },
  { id: '4M', name: 'Freedom (IN)', pId: '4S' },
  { id: '1Y', name: 'Fully Insured PPO (TN)', pId: '1L' },
  { id: '6F', name: 'Fully-Insured PPO (MI)', pId: '0B' },
  { id: '7Y', name: 'Fully-Insured PPO (CA)', pId: '1Q' },
  { id: '9Z', name: 'Georgia Exchange Plan (GA)', pId: '2F' },
  { id: 'CH', name: 'Georgia IFP Connect (GA)', pId: '1W' },
  { id: '7J', name: 'GHI (NY)', pId: '4O' },
  { id: '4P', name: 'Gold (OH)', pId: '0T' },
  { id: '6L', name: 'Gold 80 HMO (CA)', pId: '1Q' },
  { id: '43', name: 'Gold HMO (NV)', pId: '4G' },
  { id: '9W', name: 'Gold Select (NY)', pId: '0S' },
  { id: '4U', name: 'GQO PPO (PA)', pId: '2M' },
  { id: '7R', name: 'Group (GA)', pId: '2G' },
  { id: '8G', name: 'Group (UT)', pId: '2N' },
  { id: '5V', name: 'HAP HMO Henry Ford Choice (MI)', pId: '0Z' },
  { id: '8C', name: 'Harvard Pilgrim PPO (MA)', pId: '06' },
  { id: '24', name: 'Health 2 Business Health Plan (USA)', pId: '47' },
  { id: '0K', name: 'Health Advantage HMO (AR)', pId: '0V' },
  { id: 'CF', name: 'Health Insurance Marketplace (TX)', pId: '2O' },
  { id: '4H', name: 'Healthcare Highways (TX)', pId: '08' },
  { id: '9K', name: 'Healthkeepers (VA)', pId: '3A' },
  { id: '69', name: 'Healthnet (CA)', pId: '10' },
  { id: '2E', name: 'Healthnet (OR)', pId: '10' },
  { id: '4Q', name: 'HealthPlan Services (USA)', pId: '0L' },
  { id: '02', name: 'Heritage Plus POS (USA)', pId: '2F' },
  { id: '9P', name: 'Heritage Prime PPO (WA)', pId: '4T' },
  { id: '7T', name: 'HERITAGE SIGNATURE (WA)', pId: '4T' },
  { id: '7V', name: 'Highpoint POS (USA)', pId: '40' },
  { id: 'CM', name: 'HIP Commercial (NY)', pId: '4O' },
  { id: '60', name: 'HMAA (HI)', pId: '14' },
  { id: 'AE', name: 'HMO (AZ)', pId: '3B' },
  { id: '4Z', name: 'HMO (MA)', pId: '06' },
  { id: '2N', name: 'HMO (MO)', pId: '3A' },
  { id: '33', name: 'HMO (NH)', pId: '3A' },
  { id: 'A0', name: 'HMO (PA)', pId: '12' },
  { id: '2K', name: 'HMO (ME)', pId: '3A' },
  { id: '1Z', name: 'HMO (HI)', pId: '2L' },
  { id: '72', name: 'HMO (NY)', pId: '3A' },
  { id: 'CU', name: 'HMO (NV)', pId: '3A' },
  { id: '5E', name: 'HMO (VA)', pId: '3Z' },
  { id: '31', name: 'HMO (VA)', pId: '3A' },
  { id: '0V', name: 'HMO (NM)', pId: '42' },
  { id: '0O', name: 'HMO (OH)', pId: '3A' },
  { id: '13', name: 'HMO (WI)', pId: '3A' },
  { id: '5L', name: 'HMO (MD)', pId: '0W' },
  { id: '0I', name: 'HMO (CO)', pId: '3A' },
  { id: '5S', name: 'HMO (GA)', pId: '3A' },
  { id: '84', name: 'HMO (WA)', pId: '2X' },
  { id: '7B', name: 'HMO (NV)', pId: '15' },
  { id: 'C7', name: 'HMO (IN)', pId: '3A' },
  { id: '3A', name: 'HMO (CA)', pId: '3A' },
  { id: 'A9', name: 'HMO (CT)', pId: '3A' },
  { id: '7F', name: 'HMO (KY)', pId: '3A' },
  { id: 'AA', name: 'HMO (NM)', pId: '01' },
  { id: '6N', name: 'HMO - Flex (MA)', pId: '06' },
  { id: '3P', name: 'HMO - Fully Insured (MI)', pId: '0B' },
  { id: 'BG', name: 'HMO - MA (MA)', pId: '0I' },
  { id: '1E', name: 'HMO - RI (RI)', pId: '0I' },
  { id: 'CT', name: 'HMO Blue Fully-Insured (MA)', pId: '2C' },
  { id: '45', name: 'HMSA Platinum PPO (HI)', pId: '2L' },
  { id: '0W', name: 'HP Select (MN)', pId: '49' },
  { id: '4W', name: 'HPOS (MI)', pId: '2Z' },
  { id: '0N', name: 'HPS PPO (WI)', pId: '4L' },
  { id: '5O', name: 'HSA Premium (USA)', pId: '1D' },
  { id: '36', name: 'HVN (MN)', pId: '43' },
  { id: '21', name: 'ID Navigator Gold (ID)', pId: '3R' },
  { id: '4S', name: 'IHSFS (NY)', pId: '02' },
  { id: 'AH', name: 'Illinois Connect (IL)', pId: '1W' },
  { id: '0M', name: 'Illinois Exchange Plan (IL)', pId: '2F' },
  { id: '4B', name: 'Imagine 360 (USA)', pId: '1A' },
  { id: '1W', name: 'Indemnity (NJ)', pId: '41' },
  { id: '8E', name: 'Independent Health Association HMO (NY)', pId: '02' },
  { id: '0D', name: 'Indiana Connect (IN)', pId: '1W' },
  { id: '6I', name: 'Individual (GA)', pId: '2G' },
  { id: '97', name: 'Individual And Family Plan Platinum 90 (CA)', pId: '4K' },
  { id: '8Z', name: 'Individual Arizona (AZ)', pId: '1U' },
  { id: '8Y', name: 'Individual California (CA)', pId: '1U' },
  { id: '7E', name: 'Individual Cleveland (OH)', pId: '1U' },
  { id: 'AJ', name: 'Individual Columbus (OH)', pId: '1U' },
  { id: '63', name: 'Individual Florida (FL)', pId: '1U' },
  { id: '0F', name: 'Individual Georgia (GA)', pId: '1U' },
  { id: 'DB', name: 'Individual Georgia HMO Non-Gatekept (GA)', pId: '1U' },
  { id: 'DG', name: 'Individual Houston Choice (TX)', pId: '1U' },
  { id: '9C', name: 'Individual Illinois (IL)', pId: '1U' },
  { id: '5C', name: 'Individual Iowa (IA)', pId: '1U' },
  { id: '47', name: 'Individual Kansas (KS)', pId: '1U' },
  { id: '7A', name: 'Individual Michigan (MI)', pId: '1U' },
  { id: '7G', name: 'Individual Missouri (MO)', pId: '1U' },
  { id: '7M', name: 'Individual Nebraska (NE)', pId: '1U' },
  { id: '4I', name: 'Individual New Jersey (NJ)', pId: '1U' },
  { id: '4G', name: 'Individual New York (NY)', pId: '1U' },
  { id: '1S', name: 'Individual North Carolina (NC)', pId: '1U' },
  { id: 'CK', name: 'Individual Oklahoma (OK)', pId: '1U' },
  { id: '30', name: 'Individual Pennsylvania (PA)', pId: '1U' },
  { id: 'AG', name: 'Individual Tennessee (TN)', pId: '1U' },
  { id: 'CD', name: 'Individual Texas (TX)', pId: '1U' },
  { id: '85', name: 'Individual Virginia (VA)', pId: '1U' },
  { id: '9T', name: 'Innovation Health Bronze (USA)', pId: '4R' },
  { id: '1V', name: 'Kaiser Exchange GA (GA)', pId: '09' },
  { id: '6W', name: 'Kaiser Northern California Commercial (CA)', pId: '09' },
  { id: '8H', name: 'Kaiser Southern California Commercial (CA)', pId: '09' },
  { id: '2Y', name: 'Kansas Exchange Plan (KS)', pId: '2F' },
  { id: '34', name: 'KFHP (MD)', pId: '09' },
  { id: '5M', name: 'KFHP (HI)', pId: '09' },
  { id: 'A4', name: 'KFHP (CO)', pId: '09' },
  { id: '5I', name: 'KFHP Commercial 2 (WA)', pId: '09' },
  { id: 'AX', name: 'KFHP NW (OR)', pId: '09' },
  { id: '3M', name: 'Large Group PPO (NY)', pId: '46' },
  { id: 'CS', name: 'Large Group PPO (CA)', pId: '0X' },
  { id: 'AD', name: 'Large Group PPO (VA)', pId: '4M' },
  { id: '99', name: 'Large Group PPO (NY)', pId: '0S' },
  { id: '7W', name: 'Local Access HMO (CA)', pId: '1Q' },
  { id: 'D9', name: 'Localplus PPO (USA)', pId: '1W' },
  { id: '6U', name: 'Louisiana Exchange Plan (LA)', pId: '2F' },
  { id: '2H', name: 'Magnacare (USA)', pId: '1X' },
  { id: '1N', name: 'Maryland Exchange Plan (MD)', pId: '2F' },
  { id: '23', name: 'Medcost Preferred 400 (NC)', pId: '0U' },
  { id: 'AW', name: 'Medica Choice National (NE)', pId: '1F' },
  { id: '8P', name: 'Medica Choice Passport (MN)', pId: '1F' },
  { id: '7S', name: 'Medica Elect (MN)', pId: '1F' },
  { id: 'C6', name: 'Medica VantagePlus (MN)', pId: '1F' },
  { id: '8V', name: 'Medica with CHI Health (NE)', pId: '1F' },
  { id: '70', name: 'Meritain Health (USA)', pId: '1K' },
  { id: '2R', name: 'Metal Plan CHSIC PPO (MO)', pId: '3K' },
  { id: '9I', name: 'MGB ASO (MA)', pId: '24' },
  { id: '4E', name: 'MHN (CA)', pId: '3J' },
  { id: 'CJ', name: 'Michigan Exchange Plan (MI)', pId: '2F' },
  { id: 'CV', name: 'Minnesota MRFs (MN)', pId: '1F' },
  { id: '1L', name: 'Mississippi Connect (MS)', pId: '1W' },
  { id: 'CQ', name: 'Mississippi Exchange Plan (MS)', pId: '2F' },
  { id: 'A7', name: 'Missouri Exchange Plan (MO)', pId: '2F' },
  { id: 'C1', name: 'Moda Select (TX)', pId: '18' },
  { id: '2C', name: 'MPI (USA)', pId: '3F' },
  { id: 'CC', name: 'My Blue (FL)', pId: '2S' },
  { id: '17', name: 'MyBlue Health HMO (TX)', pId: '3S' },
  { id: '7L', name: 'National BH EAP (USA)', pId: '26' },
  { id: '9M', name: 'National OAP (USA)', pId: '1W' },
  { id: 'B4', name: 'National OAP SAR (USA)', pId: '1W' },
  { id: '3G', name: 'National PPO (USA)', pId: '1W' },
  { id: 'DE', name: 'National PPO Lookback Network (USA)', pId: '1W' },
  { id: '81', name: 'Navigate Balanced (USA)', pId: '2F' },
  { id: 'CW', name: 'Network Health Plan Self Funded (WI)', pId: '3P' },
  { id: '68', name: 'New England Managed Care (MA)', pId: '2C' },
  { id: '5U', name: 'New Jersey Exchange Plan (NJ)', pId: '2F' },
  { id: '9H', name: 'New Mexico Exchange Plan (NM)', pId: '2F' },
  { id: '18', name: 'Nexus ACO OAP (USA)', pId: '2F' },
  { id: '49', name: 'NHP (RI)', pId: '0E' },
  { id: 'BD', name: 'Non Diff PPO (USA)', pId: '2F' },
  { id: '2A', name: 'North Carolina Connect (NC)', pId: '1W' },
  { id: '26', name: 'North Carolina Exchange Plan (NC)', pId: '2F' },
  { id: 'DD', name: 'NYC Seamless HMO (NY)', pId: '1W' },
  { id: 'BY', name: 'OAEPO (NY)', pId: '37' },
  { id: '3R', name: 'OHIC (VA)', pId: '3Z' },
  { id: 'AR', name: 'Ohio Exchange Plan (OH)', pId: '2F' },
  { id: '3X', name: 'Ohio PPO Connect (OH)', pId: '3Y' },
  { id: 'BL', name: 'Oklahoma Exchange Plan (OK)', pId: '2F' },
  { id: '16', name: 'Open Access (MN)', pId: '49' },
  { id: 'BS', name: 'Open Access Elect Choice (USA)', pId: '37' },
  { id: '5A', name: 'Open Access Managed Choice (USA)', pId: '37' },
  { id: '20', name: 'Options (IN)', pId: '4S' },
  { id: '8J', name: 'Options PPO (USA)', pId: '2F' },
  { id: '8I', name: 'OR Navigator Gold (OR)', pId: '3R' },
  { id: '9O', name: 'Oxford Health Plan HMO Primary Advantage (NJ)', pId: '34' },
  { id: 'B7', name: 'Pacificare Signature Value Alliance (CA)', pId: '4F' },
  { id: '5B', name: 'PAR (TX)', pId: '3S' },
  { id: '9Y', name: 'PAR (NM)', pId: '01' },
  { id: '5N', name: 'PAR (MA)', pId: '2C' },
  { id: '9S', name: 'Pathway (GA)', pId: '3A' },
  { id: '0L', name: 'PBC PPO (WA)', pId: '4T' },
  { id: '5X', name: 'Pennsylvania Connect (PA)', pId: '1W' },
  { id: '6H', name: 'PHCS (USA)', pId: '3F' },
  { id: '2J', name: 'Pioneer (AK)', pId: '18' },
  { id: '2O', name: 'Platinum 90 HMO (CA)', pId: '07' },
  { id: '0A', name: 'Platinum 90 PPO (CA)', pId: '1Q' },
  { id: '6A', name: 'POS (WI)', pId: '1E' },
  { id: '0X', name: 'POS (NY)', pId: '02' },
  { id: 'AQ', name: 'POS (MI)', pId: '35' },
  { id: '0E', name: 'PPO (NH)', pId: '3A' },
  { id: '55', name: 'PPO (CT)', pId: '3A' },
  { id: '80', name: 'PPO (RI)', pId: '1T' },
  { id: '65', name: 'PPO (NV)', pId: '3A' },
  { id: 'C3', name: 'PPO (NY)', pId: '3Q' },
  { id: '5Y', name: 'PPO (NJ)', pId: '41' },
  { id: '01', name: 'PPO (OH)', pId: '04' },
  { id: '0R', name: 'PPO (WI)', pId: '1E' },
  { id: '07', name: 'PPO (WI)', pId: '03' },
  { id: 'CO', name: 'PPO (USA)', pId: '1C' },
  { id: '98', name: 'PPO (NM)', pId: '01' },
  { id: '3D', name: 'PPO (OH)', pId: '1B' },
  { id: '5D', name: 'PPO (MI)', pId: '2T' },
  { id: '2P', name: 'PPO (MS)', pId: '16' },
  { id: '0J', name: 'PPO (UT)', pId: '15' },
  { id: '8U', name: 'PPO (CO)', pId: '3A' },
  { id: '0U', name: 'PPO (VA)', pId: '3A' },
  { id: '9D', name: 'PPO (ME)', pId: '3A' },
  { id: 'AO', name: 'PPO (NY)', pId: '13' },
  { id: '5R', name: 'PPO (WV)', pId: '4C' },
  { id: '7D', name: 'PPO (PA)', pId: '12' },
  { id: '64', name: 'PPO (MI)', pId: '0Z' },
  { id: '1T', name: 'PPO (MD)', pId: '0W' },
  { id: '0H', name: 'PPO (CA)', pId: '3A' },
  { id: '41', name: 'PPO (USA)', pId: '0Q' },
  { id: 'BI', name: 'PPO (KY)', pId: '3A' },
  { id: '93', name: 'PPO (MN)', pId: '0P' },
  { id: '3C', name: 'PPO (WI)', pId: '3A' },
  { id: 'B6', name: 'PPO (GA)', pId: '3A' },
  { id: 'AF', name: 'PPO (NY)', pId: '3A' },
  { id: '59', name: 'PPO (OH)', pId: '3A' },
  { id: 'BQ', name: 'PPO (IN)', pId: '3A' },
  { id: '77', name: 'PPO (MO)', pId: '3A' },
  { id: '7U', name: 'PPO (AZ)', pId: '3B' },
  { id: '0T', name: 'PPO (IN)', pId: '22' },
  { id: '2W', name: 'PPO (NV)', pId: '3H' },
  { id: '6T', name: 'PPO (NC)', pId: '3I' },
  { id: '78', name: 'PPO (PA)', pId: '1Z' },
  { id: '2S', name: 'PPO (PA)', pId: '1Y' },
  { id: '1H', name: 'PPO - Flex (MA)', pId: '06' },
  { id: 'AN', name: 'PPO - MA (MA)', pId: '0I' },
  { id: '6X', name: 'PPO - RI (RI)', pId: '0I' },
  { id: '1J', name: 'PPO Blue (DE)', pId: '36' },
  { id: '7P', name: 'PPO VFP (VT)', pId: '0F' },
  { id: '74', name: 'Preferred (WA)', pId: '48' },
  { id: '9N', name: 'Preferred Blue (SC)', pId: '3M' },
  { id: '1A', name: 'Preferred Blue Standard (ID)', pId: '3T' },
  { id: 'BB', name: 'Preferred Care Blue (MO)', pId: '1G' },
  { id: '11', name: 'Preferred One (WI)', pId: '4H' },
  { id: 'B3', name: 'Preferred PPO (ID)', pId: '29' },
  { id: '42', name: 'Preferred PPO (OR)', pId: '4W' },
  { id: 'BU', name: 'Preferred PPO (MT)', pId: '1N' },
  { id: '2D', name: 'Preferred PPO (TX)', pId: '25' },
  { id: '6O', name: 'Preferred PPO W001 (WA)', pId: '4D' },
  { id: 'BA', name: 'Preferred SmartNET (USA)', pId: '2Y' },
  { id: '8M', name: 'Premier HMO (WI)', pId: '1P' },
  { id: '3Q', name: 'Premier HMO (TX)', pId: '25' },
  { id: 'CE', name: 'Premier POS (WI)', pId: '1P' },
  { id: '9J', name: 'Premier Select Blue Choice (NE)', pId: '2U' },
  { id: '2I', name: 'Prime Health Services (USA)', pId: '3O' },
  { id: 'C5', name: 'Priority Health HMO (MI)', pId: '1M' },
  { id: 'BX', name: 'Priority Health PPO (MI)', pId: '1M' },
  { id: '1P', name: 'ProviDRs Care (USA)', pId: '3L' },
  { id: '22', name: 'Qualchoice (TX)', pId: '11' },
  { id: '2T', name: 'Quartz Central Network State And Local (WI)', pId: '4N' },
  { id: '2Z', name: 'Realvalue (UT)', pId: '3D' },
  { id: '3U', name: 'Realvalue (WA)', pId: '3D' },
  { id: 'BF', name: 'Realvalue Gold (OR)', pId: '3D' },
  { id: '5T', name: 'Robin Focused (MN)', pId: '49' },
  { id: '4A', name: 'Robin Select (MN)', pId: '49' },
  { id: '09', name: 'Rocky Mountain Sky (CO)', pId: '2Q' },
  { id: '90', name: 'Rocky Mountain Valley (CO)', pId: '2Q' },
  { id: 'BM', name: 'Sagamore Health Network (IN)', pId: '39' },
  { id: 'AL', name: 'Sana Benefits (USA)', pId: '0D' },
  { id: '08', name: 'Select HMO (MA)', pId: '24' },
  { id: 'A2', name: 'Select Plus (USA)', pId: '2F' },
  { id: '8N', name: 'Self Funded (WI)', pId: '19' },
  { id: '0B', name: 'Short Term PPO 1000 (IL)', pId: '1S' },
  { id: '92', name: 'SHP (ND)', pId: '2J' },
  { id: 'BC', name: 'SignatureValue Harmony HMO (CA)', pId: '4F' },
  { id: 'A1', name: 'Silver Pro EPO (NY)', pId: '4I' },
  { id: '6M', name: 'Simply Virtual HMO (MA)', pId: '06' },
  { id: '05', name: 'Small Group (CA)', pId: '0X' },
  { id: '1K', name: 'South Carolina Connect (SC)', pId: '1W' },
  { id: '1D', name: 'South Carolina Exchange Plan (SC)', pId: '2F' },
  { id: '25', name: 'Standard Platinum PPO (MA)', pId: '33' },
  { id: '3N', name: 'State Group Plan (SC)', pId: '3M' },
  { id: '5G', name: 'SuperMed PPO (OH)', pId: '3E' },
  { id: 'AU', name: 'Sutter Health Plus (CA)', pId: '0X' },
  { id: 'BV', name: 'Tennessee Connect (TN)', pId: '1W' },
  { id: '9B', name: 'Tennessee Exchange Plan (TN)', pId: '2F' },
  { id: '5Z', name: 'Texas Connect (TX)', pId: '1W' },
  { id: 'B5', name: 'Texas Exchange Plan (TX)', pId: '2F' },
  { id: '2V', name: 'THP (WV)', pId: '0H' },
  { id: '1B', name: 'Traditional (KS)', pId: '2D' },
  { id: '6S', name: 'Trilogy Direct (WI)', pId: '05' },
  { id: '2F', name: 'True Blue PPO (AR)', pId: '0M' },
  { id: '71', name: 'Truli (FL)', pId: '23' },
  { id: '4O', name: 'TX Gold 8 (TX)', pId: '07' },
  { id: 'CL', name: 'U Health Healthy Premier (UT)', pId: '45' },
  { id: 'CI', name: 'UCARE (MN)', pId: '0C' },
  { id: 'C8', name: 'UHA (1142) (HI)', pId: '0Y' },
  { id: 'DC', name: 'UMR Choice Plus SEIU (USA)', pId: '2F' },
  { id: 'D8', name: 'UMR Core (USA)', pId: '2F' },
  { id: 'CR', name: 'UPMC Business Advantage PPO (PA)', pId: '3G' },
  { id: '6P', name: 'Utah Connect (UT)', pId: '1W' },
  { id: '94', name: 'Value HMO (MA)', pId: '24' },
  { id: 'C2', name: 'Virginia Connect (VA)', pId: '1W' },
  { id: '9Q', name: 'Virginia Exchange Plan (VA)', pId: '2F' },
  { id: 'A3', name: 'WA Navigator Gold (WA)', pId: '3R' },
  { id: 'AM', name: 'Washington Exchange Plan (WA)', pId: '2F' },
  { id: '8L', name: 'WHMA - Preferred (WA)', pId: '21' },
  { id: 'CB', name: 'Wisconsin Exchange Plan (WI)', pId: '2F' },
  { id: 'CY', name: 'WPS Select Plus HMO (WI)', pId: '03' },
  { id: '2G', name: 'WPS Statewide (WI)', pId: '03' },
  { id: '3E', name: 'Wyoming Total Choice PPO (WY)', pId: '2V' },
  { id: '9X', name: 'Your Choice EPO (MA)', pId: '2P' },
]