export interface Indicator {
  indicatorCode: string;
  indicatorName: string;
  indicatorDescription: string;
  indicatorGroup: 'medicare' | 'rates' | 'commercial' | 'general';
  aggregation: string;
  selected: boolean;
  format: string;
  pScale: number;
  pSymbol: string;
}

export const INDICATORS: Indicator[] =
  [
    { indicatorCode: "rate", indicatorName: "Rates", indicatorDescription: "Rate", indicatorGroup: "rates", aggregation: "q50", selected: false, pScale: 0, pSymbol: "", format: "0.00" },

    { indicatorCode: "medicaid_enrolled_lbas", indicatorName: "Geographic Distribution of  LBAs", indicatorDescription: "Medicaid Enrolled LBAs", indicatorGroup: "medicare", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "medicaid_pop_total", indicatorName: "Medicaid Enrolled Children with Autism", indicatorDescription: "Geographic Distribution of LBA.", indicatorGroup: "medicare", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },

    { indicatorCode: "cnt_entities", indicatorName: "Entities count by county", indicatorDescription: "Entities count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "cnt_ein", indicatorName: "Ein count by county", indicatorDescription: "Ein count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "cnt_networks", indicatorName: "Neworks count by county", indicatorDescription: "Networks count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "cnt_payors", indicatorName: "Payors count by county", indicatorDescription: "Payors count by county: description.", indicatorGroup: "commercial", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "bcba_d", indicatorName: "bcba_d count by county", indicatorDescription: "bcba_d count by county: description.", indicatorGroup: "commercial", aggregation: "q50", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "bcba", indicatorName: "bcba count by county", indicatorDescription: "bcba count by county: description.", indicatorGroup: "commercial", aggregation: "q50", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "bcaba", indicatorName: "bcaba count by county", indicatorDescription: "bcaba count by county: description.", indicatorGroup: "commercial", aggregation: "q50", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "rbt", indicatorName: "rbt count by county", indicatorDescription: "rbt count by county: description.", indicatorGroup: "commercial", aggregation: "q50", selected: false, pScale: 0, pSymbol: "", format: "0" },

    { indicatorCode: "population", indicatorName: "population", indicatorDescription: "population", indicatorGroup: "general", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "area", indicatorName: "Area (km2)", indicatorDescription: "Area of land in km2.", indicatorGroup: "general", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0" },
    { indicatorCode: "pop_density", indicatorName: "Population Density", indicatorDescription: "Number of inhabitants per km2.", indicatorGroup: "general", aggregation: "cnt", selected: false, pScale: 0, pSymbol: "", format: "0.0" },
  ]

// List of codes
export const CODES = [
  { id: '00000', name: 'All' },
  { id: '97151', name: '97151' },
  { id: '97152', name: '97152' },
  { id: '97153', name: '97153' },
  { id: '97154', name: '97154' },
  { id: '97155', name: '97155' },
  { id: '97156', name: '97156' },
  { id: '97157', name: '97157' },
  { id: '97158', name: '97158' },
];

// List of payors
export const PAYORS = [
  { id: 'ZZ', name: 'ALL' },
  { id: '37', name: 'Aetna' },
  { id: '2G', name: 'Alliant Health Plans' },
  { id: '3C', name: 'Allina Health' },
  { id: '24', name: 'AllWays Health Partners' },
  { id: '28', name: 'Ambetter' },
  { id: '2R', name: 'Americas PPO' },
  { id: '4E', name: 'Amerihealth Caritas Next' },
  { id: '3U', name: 'AmeriHealth Insurance Company of New Jersey' },
  { id: '3A', name: 'Anthem' },
  { id: '0M', name: 'Arkansas Blue Cross and Blue Shield' },
  { id: '4H', name: 'Aspirus Health Plan' },
  { id: '48', name: 'Asuris Northwest Health' },
  { id: '0T', name: 'AultCare Insurance Company' },
  { id: '4V', name: 'Avera Health Plans Inc' },
  { id: '4Q', name: 'AvMed' },
  { id: '25', name: 'Baylor Scott and White Health Plan' },
  { id: '1C', name: 'BCBS Puerto Rico (Triple S)' },
  { id: '38', name: 'Beacon Health Options' },
  { id: '3V', name: 'Blue Card' },
  { id: '0R', name: 'Blue Cross and Blue Shield of Illinois' },
  { id: '2D', name: 'Blue Cross and Blue Shield of Kansas' },
  { id: '1G', name: 'Blue Cross and Blue Shield of Kansas City' },
  { id: '1N', name: 'Blue Cross and Blue Shield of Montana' },
  { id: '2U', name: 'Blue Cross and Blue Shield of Nebraska' },
  { id: '01', name: 'Blue Cross and Blue Shield of New Mexico' },
  { id: '3I', name: 'Blue Cross and Blue Shield of North Carolina' },
  { id: '2K', name: 'Blue Cross and Blue Shield of Oklahoma' },
  { id: '3S', name: 'Blue Cross and Blue Shield of Texas' },
  { id: '0F', name: 'Blue Cross and Blue Shield of Vermont' },
  { id: '2V', name: 'Blue Cross and Blue Shield of Wyoming' },
  { id: '3W', name: 'Blue Cross Blue Shield Louisiana' },
  { id: '44', name: 'Blue Cross Blue Shield of Alabama' },
  { id: '3B', name: 'Blue Cross Blue Shield of Arizona' },
  { id: '2C', name: 'Blue Cross Blue Shield of Massachusetts' },
  { id: '0B', name: 'Blue Cross Blue Shield of Michigan' },
  { id: '43', name: 'Blue Cross Blue Shield of Minnesota' },
  { id: '16', name: 'Blue Cross Blue Shield of Mississippi' },
  { id: '20', name: 'Blue Cross Blue Shield of North Dakota' },
  { id: '1T', name: 'Blue Cross Blue Shield of Rhode Island' },
  { id: '3T', name: 'Blue Cross of Idaho' },
  { id: '1Q', name: 'Blue Shield of California' },
  { id: '3M', name: 'BlueCross BlueShield of South Carolina' },
  { id: '1L', name: 'BlueCross BlueShield of Tennessee' },
  { id: '3D', name: 'BridgeSpan' },
  { id: '31', name: 'Capital BlueCross' },
  { id: '2W', name: 'Capital District Physicians Health Plan' },
  { id: '4J', name: 'Capital Health Plan Inc' },
  { id: '0W', name: 'CareFirst BlueCross BlueShield' },
  { id: '4A', name: 'Caresource' },
  { id: '4P', name: 'Centivo' },
  { id: '1J', name: 'Christus' },
  { id: '1W', name: 'Cigna Corporation' },
  { id: '1V', name: 'Common Ground Healthcare Cooperative' },
  { id: '2O', name: 'Community Health Choice' },
  { id: '3X', name: 'Community Health Options' },
  { id: '1H', name: 'CommunityCare' },
  { id: '2H', name: 'ComPsych' },
  { id: '2E', name: 'Coventry Health Plan of Florida' },
  { id: '3K', name: 'Cox Health Systems' },
  { id: '17', name: 'Curative' },
  { id: '0J', name: 'DakotaCare' },
  { id: '1O', name: 'Dean Health Plan' },
  { id: '40', name: 'Denver Health Medical Plan' },
  { id: '1I', name: 'EHN' },
  { id: '4O', name: 'Emblem Health' },
  { id: '2N', name: 'EMI Health' },
  { id: '32', name: 'Encore' },
  { id: '0S', name: 'Excellus BlueCross BlueShield' },
  { id: '33', name: 'Fallon Health' },
  { id: '0A', name: 'Fidelis Care' },
  { id: '0G', name: 'First Health' },
  { id: '2S', name: 'Florida Blue' },
  { id: '2M', name: 'Geisinger Health Plan' },
  { id: '1E', name: 'Group Health Cooperative of South Central Wisconsin' },
  { id: '0Z', name: 'HAP' },
  { id: '06', name: 'Harvard Pilgrim Healthcare' },
  { id: '14', name: 'Hawaii Medical Assurance Association' },
  { id: '2L', name: 'Hawaii Medical Service Association' },
  { id: '0V', name: 'Health Advantage HMO Partners' },
  { id: '1S', name: 'Health Alliance' },
  { id: '10', name: 'Health Net' },
  { id: '0K', name: 'Health New England Inc' },
  { id: '4L', name: 'Health Payment Systems' },
  { id: '4U', name: 'Health Plan of Nevada' },
  { id: '47', name: 'Health2Business' },
  { id: '08', name: 'Healthcare Highways' },
  { id: '4I', name: 'Healthfirst' },
  { id: '49', name: 'HealthPartners' },
  { id: '0L', name: 'HealthPlan Services' },
  { id: '2Y', name: 'Healthsmart' },
  { id: '2Z', name: 'Henry Ford Health System' },
  { id: '36', name: 'Highmark Blue Cross Blue Shield Delaware' },
  { id: '1Y', name: 'Highmark Blue Cross Blue Shield Pennsylvania' },
  { id: '4C', name: 'Highmark Blue Cross Blue Shield West Virginia' },
  { id: '3Q', name: 'Highmark Blue Cross Blue Shield Western New York' },
  { id: '13', name: 'Highmark Blue Shield of Northeastern New York' },
  { id: '1Z', name: 'Highmark Blue Shield Pennsylvania' },
  { id: '21', name: 'HMA' },
  { id: '4G', name: 'Hometown Health Plan' },
  { id: '41', name: 'Horizon Blue Cross Blue Shield of New Jersey' },
  { id: '0Q', name: 'Humana' },
  { id: '1A', name: 'Imagine360' },
  { id: '12', name: 'Independence BCBS' },
  { id: '02', name: 'Independent Health' },
  { id: '4R', name: 'Innovation Health Plan' },
  { id: '09', name: 'Kaiser Foundation Health Plan' },
  { id: '2X', name: 'Lifewise' },
  { id: '1D', name: 'Magellan Health' },
  { id: '1X', name: 'MagnaCare' },
  { id: '35', name: 'McLaren' },
  { id: '0U', name: 'Medcost' },
  { id: '1F', name: 'Medica' },
  { id: '3E', name: 'Medical Mutual of Ohio' },
  { id: '19', name: 'MercyCare' },
  { id: '1K', name: 'Meritain Health' },
  { id: '3J', name: 'MHN' },
  { id: '2B', name: 'Midlands Choice' },
  { id: '18', name: 'Moda Health' },
  { id: '07', name: 'Molina Healthcare' },
  { id: '3F', name: 'MultiPlan' },
  { id: '2I', name: 'MVP Health Care' },
  { id: '0E', name: 'Neighborhood Health Plan of Rhode Island' },
  { id: '3P', name: 'Network Health' },
  { id: '3Y', name: 'Ohio PPO Connect' },
  { id: '3Z', name: 'Optima Health' },
  { id: '26', name: 'Optum' },
  { id: '1U', name: 'Oscar Insurance Corporation' },
  { id: '34', name: 'Oxford Health Plan' },
  { id: '4F', name: 'Pacificare' },
  { id: '3R', name: 'PacificSource Health Plans' },
  { id: '04', name: 'Paramount Insurance Company' },
  { id: '2T', name: 'Physicians Health Plan' },
  { id: '4S', name: 'Physicians Health Plan of Northern Indiana' },
  { id: '4M', name: 'Piedmont Health Plan' },
  { id: '2P', name: 'Point32Health' },
  { id: '0P', name: 'Preferred One' },
  { id: '4T', name: 'Premera Blue Cross' },
  { id: '42', name: 'Presbyterian Health Plan' },
  { id: '3O', name: 'Prime Health Services' },
  { id: '1M', name: 'Priority Health' },
  { id: '3H', name: 'Prominence Health Plan' },
  { id: '3L', name: 'ProviDRs Care' },
  { id: '11', name: 'Qualchoice' },
  { id: '4N', name: 'Quartz' },
  { id: '4W', name: 'Regence BlueCross BlueShield of Oregon' },
  { id: '30', name: 'Regence BlueCross BlueShield of Utah' },
  { id: '29', name: 'Regence BlueShield of Idaho' },
  { id: '4D', name: 'Regence BlueShield of Washington' },
  { id: '2Q', name: 'Rocky Mountain Health Plan' },
  { id: '39', name: 'Sagamore Health Network' },
  { id: '0D', name: 'Sana Benefits' },
  { id: '2J', name: 'Sanford Health Group' },
  { id: '1P', name: 'Security Health Plan of Wisconsin' },
  { id: '15', name: 'SelectHealth' },
  { id: '22', name: 'SIHO Insurance Services' },
  { id: '1B', name: 'Summa Care' },
  { id: '0X', name: 'Sutter Health Plus' },
  { id: '0O', name: 'Texas Health Aetna' },
  { id: '3N', name: 'The Alliance' },
  { id: '0H', name: 'The Health Plan' },
  { id: '05', name: 'Trilogy' },
  { id: '23', name: 'Truli' },
  { id: '0I', name: 'Tufts Health Plan' },
  { id: '0C', name: 'UCare' },
  { id: '0Y', name: 'UHA' },
  { id: '2F', name: 'UnitedHealthcare' },
  { id: '46', name: 'Univera Healthcare' },
  { id: '45', name: 'University of Utah Health Plans' },
  { id: '3G', name: 'UPMC Health Plan' },
  { id: '4K', name: 'Valley Health Plan' },
  { id: '4B', name: 'Wellmark Blue Cross and Blue Shield of Iowa' },
  { id: '27', name: 'Wellmark Blue Cross and Blue Shield of South Dakota' },
  { id: '1R', name: 'WellSense Health Plan' },
  { id: '2A', name: 'Western Health Advantage' },
  { id: '03', name: 'WPS Health Plan' },
  { id: '0N', name: 'Yale University Health Plan' }
];


/*
SELECT DISTINCT
	CONCAT('{id: \'', n.id36, '\', name: \'', n.name, '\', pId: \'', p.id36, '\'},') j
FROM bcba.network n
INNER JOIN bcba.payer p ON p.id = n.payor_id
*/
export const NETWORKS = [
  { id: 'ZZ', name: 'ALL', pId: '' },
  { id: '0S', name: 'Blue Community HMO', pId: '01' },
  { id: '3H', name: 'Blue Preferred PPO', pId: '01' },
  { id: '8B', name: 'Blue Preferred Plus', pId: '01' },
  { id: '98', name: 'PPO', pId: '01' },
  { id: '9A', name: 'Blue Advantage HMO', pId: '01' },
  { id: '9Y', name: 'PAR', pId: '01' },
  { id: 'AA', name: 'HMO', pId: '01' },
  { id: '0X', name: 'POS', pId: '02' },
  { id: '4S', name: 'IHSFS', pId: '02' },
  { id: '8E', name: 'Independent Health Association HMO', pId: '02' },
  { id: '07', name: 'PPO', pId: '03' },
  { id: '2G', name: 'WPS Statewide', pId: '03' },
  { id: 'CY', name: 'WPS Select Plus HMO', pId: '03' },
  { id: '01', name: 'PPO', pId: '04' },
  { id: '6S', name: 'Trilogy Direct', pId: '05' },
  { id: '1H', name: 'PPO - Flex', pId: '06' },
  { id: '2U', name: 'Focus Network - MA HMO', pId: '06' },
  { id: '38', name: 'ChoiceNet HMO', pId: '06' },
  { id: '4Z', name: 'HMO', pId: '06' },
  { id: '6M', name: 'Simply Virtual HMO', pId: '06' },
  { id: '6N', name: 'HMO - Flex', pId: '06' },
  { id: '8C', name: 'Harvard Pilgrim PPO', pId: '06' },
  { id: '0P', name: 'Confident Care Gold 1', pId: '07' },
  { id: '12', name: 'Confident Care Gold 8', pId: '07' },
  { id: '15', name: 'Confident Care Gold 8', pId: '07' },
  { id: '28', name: 'Constant Care Gold 8', pId: '07' },
  { id: '2L', name: 'Confident Care Gold 8', pId: '07' },
  { id: '2O', name: 'Platinum 90 HMO', pId: '07' },
  { id: '3K', name: 'Confident Care Gold 8', pId: '07' },
  { id: '4O', name: 'TX Gold 8', pId: '07' },
  { id: '56', name: 'Constant Care Gold 8', pId: '07' },
  { id: '8X', name: 'Constant Care Silver', pId: '07' },
  { id: '9F', name: 'Confident Care Gold 8', pId: '07' },
  { id: '9L', name: 'Constant Care Gold 8', pId: '07' },
  { id: 'B1', name: 'Constant Care Gold 8', pId: '07' },
  { id: 'BH', name: 'Confident Care Gold 8', pId: '07' },
  { id: '4H', name: 'Healthcare Highways', pId: '08' },
  { id: '1V', name: 'Kaiser Exchange GA', pId: '09' },
  { id: '34', name: 'KFHP', pId: '09' },
  { id: '5I', name: 'KFHP Commercial 2', pId: '09' },
  { id: '5M', name: 'KFHP', pId: '09' },
  { id: '6W', name: 'Kaiser Northern California Commercial', pId: '09' },
  { id: '8H', name: 'Kaiser Southern California Commercial', pId: '09' },
  { id: 'A4', name: 'KFHP', pId: '09' },
  { id: 'AX', name: 'KFHP NW', pId: '09' },
  { id: 'BO', name: 'Essential', pId: '0A' },
  { id: 'BW', name: 'Care Gold', pId: '0A' },
  { id: '3P', name: 'HMO - Fully Insured', pId: '0B' },
  { id: '6F', name: 'Fully-Insured PPO', pId: '0B' },
  { id: 'CI', name: 'UCARE', pId: '0C' },
  { id: 'AL', name: 'Sana Benefits', pId: '0D' },
  { id: '49', name: 'NHP', pId: '0E' },
  { id: '7P', name: 'PPO VFP', pId: '0F' },
  { id: '51', name: 'FH Umbrella', pId: '0G' },
  { id: '2V', name: 'THP', pId: '0H' },
  { id: '1E', name: 'HMO - RI', pId: '0I' },
  { id: '2B', name: 'Direct Subsidized Individual', pId: '0I' },
  { id: '6X', name: 'PPO - RI', pId: '0I' },
  { id: '86', name: 'Direct Nonsubsidized Individual', pId: '0I' },
  { id: 'AN', name: 'PPO - MA', pId: '0I' },
  { id: 'BG', name: 'HMO - MA', pId: '0I' },
  { id: 'CX', name: 'Direct Nonsubsidized Group', pId: '0I' },
  { id: '6G', name: 'DakotaCare Administrative Services', pId: '0J' },
  { id: '2M', name: 'ConnectorCare Health New England', pId: '0K' },
  { id: '7Z', name: 'Commercial Fully Funded', pId: '0K' },
  { id: '4Q', name: 'HealthPlan Services', pId: '0L' },
  { id: '2F', name: 'True Blue PPO', pId: '0M' },
  { id: 'A5', name: 'Custom', pId: '0N' },
  { id: '89', name: 'Aetna PPO', pId: '0O' },
  { id: '93', name: 'PPO', pId: '0P' },
  { id: '41', name: 'PPO', pId: '0Q' },
  { id: '3Y', name: 'Blue Advantage HMO', pId: '0R' },
  { id: '79', name: 'Blue Options PPO', pId: '0R' },
  { id: '29', name: 'Excellus BCBS HMO', pId: '0S' },
  { id: '99', name: 'Large Group PPO', pId: '0S' },
  { id: '9W', name: 'Gold Select', pId: '0S' },
  { id: '4P', name: 'Gold', pId: '0T' },
  { id: '23', name: 'Medcost Preferred 400', pId: '0U' },
  { id: '0K', name: 'Health Advantage HMO', pId: '0V' },
  { id: '1T', name: 'PPO', pId: '0W' },
  { id: '5L', name: 'HMO', pId: '0W' },
  { id: '05', name: 'Small Group', pId: '0X' },
  { id: 'AU', name: 'Sutter Health Plus', pId: '0X' },
  { id: 'CS', name: 'Large Group PPO', pId: '0X' },
  { id: 'C8', name: 'UHA (1142)', pId: '0Y' },
  { id: '5V', name: 'HAP HMO Henry Ford Choice', pId: '0Z' },
  { id: '64', name: 'PPO', pId: '0Z' },
  { id: '2E', name: 'Healthnet', pId: '10' },
  { id: '69', name: 'Healthnet', pId: '10' },
  { id: '22', name: 'Qualchoice', pId: '11' },
  { id: '7D', name: 'PPO', pId: '12' },
  { id: 'A0', name: 'HMO', pId: '12' },
  { id: 'AO', name: 'PPO', pId: '13' },
  { id: '60', name: 'HMAA', pId: '14' },
  { id: '0J', name: 'PPO', pId: '15' },
  { id: '7B', name: 'HMO', pId: '15' },
  { id: '2P', name: 'PPO', pId: '16' },
  { id: 'AP', name: 'Curative PPO', pId: '17' },
  { id: '2J', name: 'Pioneer', pId: '18' },
  { id: '8F', name: 'Endeavor Providence', pId: '18' },
  { id: '8R', name: 'Endeavor Select', pId: '18' },
  { id: 'C1', name: 'Moda Select', pId: '18' },
  { id: 'CZ', name: 'Connexus', pId: '18' },
  { id: '8N', name: 'Self Funded', pId: '19' },
  { id: 'AI', name: 'EPO', pId: '19' },
  { id: '4B', name: 'Imagine 360', pId: '1A' },
  { id: '3D', name: 'PPO', pId: '1B' },
  { id: 'CO', name: 'PPO', pId: '1C' },
  { id: '5O', name: 'HSA Premium', pId: '1D' },
  { id: '0R', name: 'PPO', pId: '1E' },
  { id: '6A', name: 'POS', pId: '1E' },
  { id: '1C', name: 'Essentia Choice Care', pId: '1F' },
  { id: '7S', name: 'Medica Elect', pId: '1F' },
  { id: '8P', name: 'Medica Choice Passport', pId: '1F' },
  { id: '8V', name: 'Medica with CHI Health', pId: '1F' },
  { id: 'AW', name: 'Medica Choice National', pId: '1F' },
  { id: 'C6', name: 'Medica VantagePlus', pId: '1F' },
  { id: 'CV', name: 'Minnesota MRFs', pId: '1F' },
  { id: 'BB', name: 'Preferred Care Blue', pId: '1G' },
  { id: '9V', name: 'Community Care', pId: '1H' },
  { id: '50', name: 'EHN', pId: '1I' },
  { id: '4L', name: 'CHP', pId: '1J' },
  { id: 'BE', name: 'CHP', pId: '1J' },
  { id: '70', name: 'Meritain Health', pId: '1K' },
  { id: '1Y', name: 'Fully Insured PPO', pId: '1L' },
  { id: 'BX', name: 'Priority Health PPO', pId: '1M' },
  { id: 'C5', name: 'Priority Health HMO', pId: '1M' },
  { id: '4N', name: 'Blue Focus POS', pId: '1N' },
  { id: 'B0', name: 'Blue Options PPO', pId: '1N' },
  { id: 'BU', name: 'Preferred PPO', pId: '1N' },
  { id: '3O', name: 'Dean Health Plan Commercial PPO', pId: '1O' },
  { id: '2X', name: 'Centercare POS', pId: '1P' },
  { id: '8M', name: 'Premier HMO', pId: '1P' },
  { id: 'CE', name: 'Premier POS', pId: '1P' },
  { id: '0A', name: 'Platinum 90 PPO', pId: '1Q' },
  { id: '6L', name: 'Gold 80 HMO', pId: '1Q' },
  { id: '7W', name: 'Local Access HMO', pId: '1Q' },
  { id: '7Y', name: 'Fully-Insured PPO', pId: '1Q' },
  { id: '1R', name: 'BMC HealthNet Silver', pId: '1R' },
  { id: '0B', name: 'Short Term PPO 1000', pId: '1S' },
  { id: '80', name: 'PPO', pId: '1T' },
  { id: '0F', name: 'Individual Georgia', pId: '1U' },
  { id: '1S', name: 'Individual North Carolina', pId: '1U' },
  { id: '30', name: 'Individual Pennsylvania', pId: '1U' },
  { id: '47', name: 'Individual Kansas', pId: '1U' },
  { id: '4G', name: 'Individual New York', pId: '1U' },
  { id: '4I', name: 'Individual New Jersey', pId: '1U' },
  { id: '5C', name: 'Individual Iowa', pId: '1U' },
  { id: '63', name: 'Individual Florida', pId: '1U' },
  { id: '7A', name: 'Individual Michigan', pId: '1U' },
  { id: '7E', name: 'Individual Cleveland', pId: '1U' },
  { id: '7G', name: 'Individual Missouri', pId: '1U' },
  { id: '7M', name: 'Individual Nebraska', pId: '1U' },
  { id: '85', name: 'Individual Virginia', pId: '1U' },
  { id: '8Y', name: 'Individual California', pId: '1U' },
  { id: '8Z', name: 'Individual Arizona', pId: '1U' },
  { id: '9C', name: 'Individual Illinois', pId: '1U' },
  { id: 'AG', name: 'Individual Tennessee', pId: '1U' },
  { id: 'AJ', name: 'Individual Columbus', pId: '1U' },
  { id: 'CD', name: 'Individual Texas', pId: '1U' },
  { id: 'CK', name: 'Individual Oklahoma', pId: '1U' },
  { id: '8O', name: 'CGHC', pId: '1V' },
  { id: '0D', name: 'Indiana Connect', pId: '1W' },
  { id: '1K', name: 'South Carolina Connect', pId: '1W' },
  { id: '1L', name: 'Mississippi Connect', pId: '1W' },
  { id: '2A', name: 'North Carolina Connect', pId: '1W' },
  { id: '3G', name: 'National PPO', pId: '1W' },
  { id: '40', name: 'Arizona Connect', pId: '1W' },
  { id: '5J', name: 'Florida Connect', pId: '1W' },
  { id: '5X', name: 'Pennsylvania Connect', pId: '1W' },
  { id: '5Z', name: 'Texas Connect', pId: '1W' },
  { id: '6P', name: 'Utah Connect', pId: '1W' },
  { id: '88', name: 'Cigna Pathwell PPO', pId: '1W' },
  { id: '9M', name: 'National OAP', pId: '1W' },
  { id: 'AH', name: 'Illinois Connect', pId: '1W' },
  { id: 'B4', name: 'National OAP SAR', pId: '1W' },
  { id: 'BV', name: 'Tennessee Connect', pId: '1W' },
  { id: 'C2', name: 'Virginia Connect', pId: '1W' },
  { id: 'CH', name: 'Georgia IFP Connect', pId: '1W' },
  { id: 'CN', name: 'Colorado Connect', pId: '1W' },
  { id: 'D9', name: 'Localplus PPO', pId: '1W' },
  { id: '2H', name: 'Magnacare', pId: '1X' },
  { id: '2S', name: 'PPO', pId: '1Y' },
  { id: '78', name: 'PPO', pId: '1Z' },
  { id: 'D5', name: 'Blue Choice Primecare', pId: '20' },
  { id: '8L', name: 'WHMA - Preferred', pId: '21' },
  { id: '0T', name: 'PPO', pId: '22' },
  { id: '71', name: 'Truli', pId: '23' },
  { id: '08', name: 'Select HMO', pId: '24' },
  { id: '35', name: 'Allies HMO', pId: '24' },
  { id: '5F', name: 'Commercial HMO', pId: '24' },
  { id: '66', name: 'Commercial PPO', pId: '24' },
  { id: '94', name: 'Value HMO', pId: '24' },
  { id: '9I', name: 'MGB ASO', pId: '24' },
  { id: '2D', name: 'Preferred PPO', pId: '25' },
  { id: '3Q', name: 'Premier HMO', pId: '25' },
  { id: '7L', name: 'National BH EAP', pId: '26' },
  { id: 'A8', name: 'Blue Select PPO', pId: '27' },
  { id: '14', name: 'Ambetter Exchange OH', pId: '28' },
  { id: '19', name: 'Ambetter Exchange TN', pId: '28' },
  { id: '1M', name: 'Ambetter Exchange PA', pId: '28' },
  { id: '1U', name: 'Ambetter Exchange AZ', pId: '28' },
  { id: '37', name: 'Ambetter Exchange MI', pId: '28' },
  { id: '3S', name: 'Ambetter Exchange LA', pId: '28' },
  { id: '3T', name: 'Ambetter Exchange NJ', pId: '28' },
  { id: '44', name: 'Ambetter Exchange KS', pId: '28' },
  { id: '4C', name: 'Ambetter Exchange NE', pId: '28' },
  { id: '4F', name: 'Ambetter Exchange NM', pId: '28' },
  { id: '4K', name: 'Ambetter Exchange WA', pId: '28' },
  { id: '4R', name: 'Ambetter Exchange TX', pId: '28' },
  { id: '4V', name: 'Ambetter Exchange MO', pId: '28' },
  { id: '5W', name: 'Ambetter Exchange IL', pId: '28' },
  { id: '6B', name: 'Ambetter Exchange MS', pId: '28' },
  { id: '6C', name: 'Ambetter Exchange KY', pId: '28' },
  { id: '6Z', name: 'Ambetter Exchange NC', pId: '28' },
  { id: '7C', name: 'Ambetter Exchange DE', pId: '28' },
  { id: '8K', name: 'Ambetter Exchange AR', pId: '28' },
  { id: '9E', name: 'Ambetter Exchange AL', pId: '28' },
  { id: '9G', name: 'Ambetter Exchange FL', pId: '28' },
  { id: 'AV', name: 'Ambetter Exchange NH', pId: '28' },
  { id: 'BZ', name: 'Ambetter Exchange IN', pId: '28' },
  { id: 'C0', name: 'Ambetter Exchange GA', pId: '28' },
  { id: 'C9', name: 'Ambetter Exchange NV', pId: '28' },
  { id: 'D0', name: 'Ambetter Exchange OK', pId: '28' },
  { id: 'D2', name: 'Ambetter Exchange SC', pId: '28' },
  { id: 'D4', name: 'Ambetter Exchange CA', pId: '28' },
  { id: 'B3', name: 'Preferred PPO', pId: '29' },
  { id: '3J', name: 'Advantage HMO', pId: '2A' },
  { id: '67', name: '3M', pId: '2B' },
  { id: '5N', name: 'PAR', pId: '2C' },
  { id: '68', name: 'New England Managed Care', pId: '2C' },
  { id: 'B9', name: 'Blue Care Elect', pId: '2C' },
  { id: 'CT', name: 'HMO Blue Fully-Insured', pId: '2C' },
  { id: '1B', name: 'Traditional', pId: '2D' },
  { id: '1O', name: 'Coventry Aetna CVS Silver', pId: '2E' },
  { id: '02', name: 'Heritage Plus POS', pId: '2F' },
  { id: '0C', name: 'Choice Plus', pId: '2F' },
  { id: '0M', name: 'Illinois Exchange Plan', pId: '2F' },
  { id: '18', name: 'Nexus ACO OAP', pId: '2F' },
  { id: '1D', name: 'South Carolina Exchange Plan', pId: '2F' },
  { id: '1N', name: 'Maryland Exchange Plan', pId: '2F' },
  { id: '1X', name: 'Florida Exchange Plan', pId: '2F' },
  { id: '26', name: 'North Carolina Exchange Plan', pId: '2F' },
  { id: '2Y', name: 'Kansas Exchange Plan', pId: '2F' },
  { id: '3L', name: 'Doctors Plan', pId: '2F' },
  { id: '5U', name: 'New Jersey Exchange Plan', pId: '2F' },
  { id: '6J', name: 'Alabama Exchange Plan', pId: '2F' },
  { id: '6U', name: 'Louisiana Exchange Plan', pId: '2F' },
  { id: '7X', name: 'Arizona Exchange Plan', pId: '2F' },
  { id: '81', name: 'Navigate Balanced', pId: '2F' },
  { id: '8J', name: 'Options PPO', pId: '2F' },
  { id: '8Q', name: 'Core', pId: '2F' },
  { id: '9B', name: 'Tennessee Exchange Plan', pId: '2F' },
  { id: '9H', name: 'New Mexico Exchange Plan', pId: '2F' },
  { id: '9Q', name: 'Virginia Exchange Plan', pId: '2F' },
  { id: '9Z', name: 'Georgia Exchange Plan', pId: '2F' },
  { id: 'A2', name: 'Select Plus', pId: '2F' },
  { id: 'A7', name: 'Missouri Exchange Plan', pId: '2F' },
  { id: 'AM', name: 'Washington Exchange Plan', pId: '2F' },
  { id: 'AR', name: 'Ohio Exchange Plan', pId: '2F' },
  { id: 'AT', name: 'Charter Balanced', pId: '2F' },
  { id: 'B5', name: 'Texas Exchange Plan', pId: '2F' },
  { id: 'BD', name: 'Non Diff PPO', pId: '2F' },
  { id: 'BL', name: 'Oklahoma Exchange Plan', pId: '2F' },
  { id: 'CB', name: 'Wisconsin Exchange Plan', pId: '2F' },
  { id: 'CJ', name: 'Michigan Exchange Plan', pId: '2F' },
  { id: 'CQ', name: 'Mississippi Exchange Plan', pId: '2F' },
  { id: 'D8', name: 'UMR Core', pId: '2F' },
  { id: '6I', name: 'Individual', pId: '2G' },
  { id: '7R', name: 'Group', pId: '2G' },
  { id: '95', name: 'ComPsych', pId: '2H' },
  { id: '0G', name: 'EPO PPO', pId: '2I' },
  { id: '92', name: 'SHP', pId: '2J' },
  { id: '39', name: 'Blue Advantage PPO', pId: '2K' },
  { id: '4X', name: 'Blue Options PPO', pId: '2K' },
  { id: 'AY', name: 'Blue Choice PPO', pId: '2K' },
  { id: 'B8', name: 'Blue Preferred PPO', pId: '2K' },
  { id: 'BJ', name: 'Blue Traditional PAR', pId: '2K' },
  { id: 'BP', name: 'Blue Lincs HMO', pId: '2K' },
  { id: '1Z', name: 'HMO', pId: '2L' },
  { id: '45', name: 'HMSA Platinum PPO', pId: '2L' },
  { id: '4U', name: 'GQO PPO', pId: '2M' },
  { id: '8G', name: 'Group', pId: '2N' },
  { id: '1F', name: 'Bronze', pId: '2O' },
  { id: 'CF', name: 'Health Insurance Marketplace', pId: '2O' },
  { id: '9X', name: 'Your Choice EPO', pId: '2P' },
  { id: '04', name: 'Colorado Exchange Plan', pId: '2Q' },
  { id: '09', name: 'Rocky Mountain Sky', pId: '2Q' },
  { id: '90', name: 'Rocky Mountain Valley', pId: '2Q' },
  { id: '9R', name: 'Colorado Doctors Plan', pId: '2Q' },
  { id: 'AC', name: 'Americas PPO', pId: '2R' },
  { id: '3W', name: 'Blue Options PPO', pId: '2S' },
  { id: '76', name: 'BlueChoice', pId: '2S' },
  { id: '82', name: 'Bluecare', pId: '2S' },
  { id: 'CC', name: 'My Blue', pId: '2S' },
  { id: '5D', name: 'PPO', pId: '2T' },
  { id: '9J', name: 'Premier Select Blue Choice', pId: '2U' },
  { id: '3E', name: 'Wyoming Total Choice PPO', pId: '2V' },
  { id: '62', name: 'CDPHP', pId: '2W' },
  { id: '84', name: 'HMO', pId: '2X' },
  { id: 'BA', name: 'Preferred SmartNET', pId: '2Y' },
  { id: '4W', name: 'HPOS', pId: '2Z' },
  { id: '4J', name: 'Blue Options PPO', pId: '30' },
  { id: '61', name: 'Capital Blue Cross', pId: '31' },
  { id: 'BR', name: 'Encore Combined', pId: '32' },
  { id: '25', name: 'Standard Platinum PPO', pId: '33' },
  { id: '9O', name: 'Oxford Health Plan HMO Primary Advantage', pId: '34' },
  { id: 'AQ', name: 'POS', pId: '35' },
  { id: '1J', name: 'PPO Blue', pId: '36' },
  { id: '06', name: 'Aetna CVS Exchange Georgia', pId: '37' },
  { id: '0Q', name: 'Aetna CVS Exchange Texas', pId: '37' },
  { id: '0Y', name: 'Aetna CVS Exchange Kansas', pId: '37' },
  { id: '10', name: 'Aetna PPO', pId: '37' },
  { id: '27', name: 'Aetna HMO', pId: '37' },
  { id: '2Q', name: 'Aetna CVS Exchange Delaware', pId: '37' },
  { id: '3F', name: 'Aetna CVS Exchange Indiana', pId: '37' },
  { id: '3V', name: 'Aetna CVS Exchange Ohio', pId: '37' },
  { id: '48', name: 'Aetna EPO', pId: '37' },
  { id: '4Y', name: 'Aetna Gold', pId: '37' },
  { id: '54', name: 'Aetna CVS Exchange New Jersey', pId: '37' },
  { id: '58', name: 'Aetna HMO', pId: '37' },
  { id: '5A', name: 'Open Access Managed Choice', pId: '37' },
  { id: '5P', name: 'Aetna HMO', pId: '37' },
  { id: '6K', name: 'Aetna CVS Exchange Florida', pId: '37' },
  { id: '6Q', name: 'Aetna CVS Exchange Illinois', pId: '37' },
  { id: '6R', name: 'Aetna HMO', pId: '37' },
  { id: '6Y', name: 'Aetna HMO', pId: '37' },
  { id: '73', name: 'Aetna CVS Exchange North Carolina', pId: '37' },
  { id: '7H', name: 'Aetna HMO', pId: '37' },
  { id: '7Q', name: 'Aetna CVS Exchange Virginia', pId: '37' },
  { id: '8A', name: 'Aetna CVS Exchange Nevada', pId: '37' },
  { id: '8S', name: 'ASA', pId: '37' },
  { id: '8T', name: 'Aetna CVS Exchange Maryland', pId: '37' },
  { id: 'AS', name: 'Aetna CVS Exchange Missouri', pId: '37' },
  { id: 'BS', name: 'Open Access Elect Choice', pId: '37' },
  { id: 'BT', name: 'Aetna National Gold HMO', pId: '37' },
  { id: 'BY', name: 'OAEPO', pId: '37' },
  { id: 'C4', name: 'Aetna CVS Exchange Utah', pId: '37' },
  { id: 'CP', name: 'Aetna CVS Exchange California', pId: '37' },
  { id: 'D3', name: 'Aetna HMO', pId: '37' },
  { id: '52', name: 'Beacon Health Options', pId: '38' },
  { id: 'BM', name: 'Sagamore Health Network', pId: '39' },
  { id: '0E', name: 'PPO', pId: '3A' },
  { id: '0H', name: 'PPO', pId: '3A' },
  { id: '0I', name: 'HMO', pId: '3A' },
  { id: '0O', name: 'HMO', pId: '3A' },
  { id: '0U', name: 'PPO', pId: '3A' },
  { id: '13', name: 'HMO', pId: '3A' },
  { id: '2K', name: 'HMO', pId: '3A' },
  { id: '2N', name: 'HMO', pId: '3A' },
  { id: '31', name: 'HMO', pId: '3A' },
  { id: '33', name: 'HMO', pId: '3A' },
  { id: '3A', name: 'HMO', pId: '3A' },
  { id: '3C', name: 'PPO', pId: '3A' },
  { id: '55', name: 'PPO', pId: '3A' },
  { id: '59', name: 'PPO', pId: '3A' },
  { id: '5S', name: 'HMO', pId: '3A' },
  { id: '65', name: 'PPO', pId: '3A' },
  { id: '72', name: 'HMO', pId: '3A' },
  { id: '77', name: 'PPO', pId: '3A' },
  { id: '7F', name: 'HMO', pId: '3A' },
  { id: '8U', name: 'PPO', pId: '3A' },
  { id: '9D', name: 'PPO', pId: '3A' },
  { id: '9K', name: 'Healthkeepers', pId: '3A' },
  { id: '9S', name: 'Pathway', pId: '3A' },
  { id: 'A9', name: 'HMO', pId: '3A' },
  { id: 'AF', name: 'PPO', pId: '3A' },
  { id: 'B6', name: 'PPO', pId: '3A' },
  { id: 'BI', name: 'PPO', pId: '3A' },
  { id: 'BQ', name: 'PPO', pId: '3A' },
  { id: 'C7', name: 'HMO', pId: '3A' },
  { id: 'CU', name: 'HMO', pId: '3A' },
  { id: '7U', name: 'PPO', pId: '3B' },
  { id: 'AE', name: 'HMO', pId: '3B' },
  { id: '53', name: 'Allina Health Aetna', pId: '3C' },
  { id: '2Z', name: 'Realvalue', pId: '3D' },
  { id: '3U', name: 'Realvalue', pId: '3D' },
  { id: 'BF', name: 'Realvalue Gold', pId: '3D' },
  { id: '5G', name: 'SuperMed PPO', pId: '3E' },
  { id: '91', name: 'All MMO', pId: '3E' },
  { id: '2C', name: 'MPI', pId: '3F' },
  { id: '6H', name: 'PHCS', pId: '3F' },
  { id: 'CR', name: 'UPMC Business Advantage PPO', pId: '3G' },
  { id: '2W', name: 'PPO', pId: '3H' },
  { id: '6T', name: 'PPO', pId: '3I' },
  { id: '7K', name: 'Blue HPN Atrium', pId: '3I' },
  { id: '8D', name: 'Blue Value Network', pId: '3I' },
  { id: '4E', name: 'MHN', pId: '3J' },
  { id: '2R', name: 'Metal Plan CHSIC PPO', pId: '3K' },
  { id: 'BK', name: 'All Files', pId: '3K' },
  { id: '1P', name: 'ProviDRs Care', pId: '3L' },
  { id: '3N', name: 'State Group Plan', pId: '3M' },
  { id: '6V', name: 'Blue Essentials', pId: '3M' },
  { id: '9N', name: 'Preferred Blue', pId: '3M' },
  { id: 'AZ', name: 'Blue Options PPO', pId: '3M' },
  { id: '3I', name: 'Alliance Comprehensive', pId: '3N' },
  { id: '7I', name: 'Alliance Premier', pId: '3N' },
  { id: '2I', name: 'Prime Health Services', pId: '3O' },
  { id: 'CW', name: 'Network Health Plan Self Funded', pId: '3P' },
  { id: 'C3', name: 'PPO', pId: '3Q' },
  { id: '21', name: 'ID Navigator Gold', pId: '3R' },
  { id: '8I', name: 'OR Navigator Gold', pId: '3R' },
  { id: 'A3', name: 'WA Navigator Gold', pId: '3R' },
  { id: '17', name: 'MyBlue Health HMO', pId: '3S' },
  { id: '1I', name: 'Blue Essentials', pId: '3S' },
  { id: '57', name: 'Blue Advantage HMO', pId: '3S' },
  { id: '5B', name: 'PAR', pId: '3S' },
  { id: '5K', name: 'Blue Premier', pId: '3S' },
  { id: 'D1', name: 'Blue Choice PPO', pId: '3S' },
  { id: '03', name: 'Blue Value Network', pId: '3T' },
  { id: '1A', name: 'Preferred Blue Standard', pId: '3T' },
  { id: '6E', name: 'Commercial PPO', pId: '3U' },
  { id: '8W', name: 'Dart Container of Michigan', pId: '3V' },
  { id: '32', name: 'Blue POS', pId: '3W' },
  { id: '7N', name: 'Blue Saver', pId: '3W' },
  { id: '4T', name: 'CHO', pId: '3X' },
  { id: '3X', name: 'Ohio PPO Connect', pId: '3Y' },
  { id: '3R', name: 'OHIC', pId: '3Z' },
  { id: '5E', name: 'HMO', pId: '3Z' },
  { id: '7V', name: 'Highpoint POS', pId: '40' },
  { id: '0Z', name: 'EPO', pId: '41' },
  { id: '1W', name: 'Indemnity', pId: '41' },
  { id: '5Y', name: 'PPO', pId: '41' },
  { id: '0V', name: 'HMO', pId: '42' },
  { id: '36', name: 'HVN', pId: '43' },
  { id: '46', name: 'Aware', pId: '43' },
  { id: 'D6', name: 'All Minnesota', pId: '43' },
  { id: '87', name: 'Blue Choice Platinum for Business', pId: '44' },
  { id: 'CL', name: 'U Health Healthy Premier', pId: '45' },
  { id: '3M', name: 'Large Group PPO', pId: '46' },
  { id: '75', name: 'Essential Plan', pId: '46' },
  { id: '24', name: 'Health 2 Business Health Plan', pId: '47' },
  { id: '74', name: 'Preferred', pId: '48' },
  { id: '0W', name: 'HP Select', pId: '49' },
  { id: '16', name: 'Open Access', pId: '49' },
  { id: '4A', name: 'Robin Select', pId: '49' },
  { id: '5T', name: 'Robin Focused', pId: '49' },
  { id: '96', name: 'Achieve', pId: '49' },
  { id: 'AK', name: 'Cornerstone', pId: '49' },
  { id: '3B', name: 'Caresource Marketplace IN', pId: '4A' },
  { id: '3Z', name: 'Caresource Marketplace WV', pId: '4A' },
  { id: '5Q', name: 'Caresource Marketplace OH', pId: '4A' },
  { id: '7O', name: 'Caresource Marketplace KY', pId: '4A' },
  { id: '9U', name: 'Caresource Marketplace NC', pId: '4A' },
  { id: 'BN', name: 'Caresource Marketplace GA', pId: '4A' },
  { id: '83', name: 'Alliance Select PPO', pId: '4B' },
  { id: '5R', name: 'PPO', pId: '4C' },
  { id: '6O', name: 'Preferred PPO W001', pId: '4D' },
  { id: '5H', name: 'AmeriHealth Bronze - Limited', pId: '4E' },
  { id: 'AB', name: 'AmeriHealth Bronze -- Limited', pId: '4E' },
  { id: 'CG', name: 'AmeriHealth Bronze - Limited', pId: '4E' },
  { id: 'B7', name: 'Pacificare Signature Value Alliance', pId: '4F' },
  { id: 'BC', name: 'SignatureValue Harmony HMO', pId: '4F' },
  { id: '43', name: 'Gold HMO', pId: '4G' },
  { id: '11', name: 'Preferred One', pId: '4H' },
  { id: 'A1', name: 'Silver Pro EPO', pId: '4I' },
  { id: 'B2', name: 'Commercial PPO', pId: '4J' },
  { id: '97', name: 'Individual And Family Plan Platinum 90', pId: '4K' },
  { id: 'D7', name: 'CoveredCalifornia Platinum AIAN', pId: '4K' },
  { id: '0N', name: 'HPS PPO', pId: '4L' },
  { id: 'AD', name: 'Large Group PPO', pId: '4M' },
  { id: '2T', name: 'Quartz Central Network State And Local', pId: '4N' },
  { id: '7J', name: 'GHI', pId: '4O' },
  { id: 'CA', name: 'Connecticare', pId: '4O' },
  { id: 'CM', name: 'HIP Commercial', pId: '4O' },
  { id: 'A6', name: 'ACTBLIZPP', pId: '4P' },
  { id: '1Q', name: 'AvMed Entrust Gold 125-ON22', pId: '4Q' },
  { id: '9T', name: 'Innovation Health Bronze', pId: '4R' },
  { id: '20', name: 'Options', pId: '4S' },
  { id: '4M', name: 'Freedom', pId: '4S' },
  { id: '0L', name: 'PBC PPO', pId: '4T' },
  { id: '1G', name: 'AK Heritage', pId: '4T' },
  { id: '7T', name: 'HERITAGE SIGNATURE', pId: '4T' },
  { id: '9P', name: 'Heritage Prime PPO', pId: '4T' },
  { id: '6D', name: 'Commercial HMO', pId: '4U' },
  { id: '4D', name: 'AHP', pId: '4V' },
  { id: '42', name: 'Preferred PPO', pId: '4W' }
]
