
import { StateData } from "./states-data-i"

export const STATES_DATA: StateData[] = [
    {"state_name": "Alabama", "state_code": "AL", "state_fp": "01"},
    {"state_name": "Alaska", "state_code": "AK", "state_fp": "02"},
    {"state_name": "Arizona", "state_code": "AZ", "state_fp": "04"},
    {"state_name": "Arkansas", "state_code": "AR", "state_fp": "05"},
    {"state_name": "California", "state_code": "CA", "state_fp": "06"},
    {"state_name": "Colorado", "state_code": "CO", "state_fp": "08"},
    {"state_name": "Connecticut", "state_code": "CT", "state_fp": "09"},
    {"state_name": "Delaware", "state_code": "DE", "state_fp": "10"},
    {"state_name": "Florida", "state_code": "FL", "state_fp": "12"},
    {"state_name": "Georgia", "state_code": "GA", "state_fp": "13"},
    {"state_name": "Hawaii", "state_code": "HI", "state_fp": "15"},
    {"state_name": "Idaho", "state_code": "ID", "state_fp": "16"},
    {"state_name": "Illinois", "state_code": "IL", "state_fp": "17"},
    {"state_name": "Indiana", "state_code": "IN", "state_fp": "18"},
    {"state_name": "Iowa", "state_code": "IA", "state_fp": "19"},
    {"state_name": "Kansas", "state_code": "KS", "state_fp": "20"},
    {"state_name": "Kentucky", "state_code": "KY", "state_fp": "21"},
    {"state_name": "Louisiana", "state_code": "LA", "state_fp": "22"},
    {"state_name": "Maine", "state_code": "ME", "state_fp": "23"},
    {"state_name": "Maryland", "state_code": "MD", "state_fp": "24"},
    {"state_name": "Massachusetts", "state_code": "MA", "state_fp": "25"},
    {"state_name": "Michigan", "state_code": "MI", "state_fp": "26"},
    {"state_name": "Minnesota", "state_code": "MN", "state_fp": "27"},
    {"state_name": "Mississippi", "state_code": "MS", "state_fp": "28"},
    {"state_name": "Missouri", "state_code": "MO", "state_fp": "29"},
    {"state_name": "Montana", "state_code": "MT", "state_fp": "30"},
    {"state_name": "Nebraska", "state_code": "NE", "state_fp": "31"},
    {"state_name": "Nevada", "state_code": "NV", "state_fp": "32"},
    {"state_name": "New Hampshire", "state_code": "NH", "state_fp": "33"},
    {"state_name": "New Jersey", "state_code": "NJ", "state_fp": "34"},
    {"state_name": "New Mexico", "state_code": "NM", "state_fp": "35"},
    {"state_name": "New York", "state_code": "NY", "state_fp": "36"},
    {"state_name": "North Carolina", "state_code": "NC", "state_fp": "37"},
    {"state_name": "North Dakota", "state_code": "ND", "state_fp": "38"},
    {"state_name": "Ohio", "state_code": "OH", "state_fp": "39"},
    {"state_name": "Oklahoma", "state_code": "OK", "state_fp": "40"},
    {"state_name": "Oregon", "state_code": "OR", "state_fp": "41"},
    {"state_name": "Pennsylvania", "state_code": "PA", "state_fp": "42"},
    {"state_name": "Rhode Island", "state_code": "RI", "state_fp": "44"},
    {"state_name": "South Carolina", "state_code": "SC", "state_fp": "45"},
    {"state_name": "South Dakota", "state_code": "SD", "state_fp": "46"},
    {"state_name": "Tennessee", "state_code": "TN", "state_fp": "47"},
    {"state_name": "Texas", "state_code": "TX", "state_fp": "48"},
    {"state_name": "Utah", "state_code": "UT", "state_fp": "49"},
    {"state_name": "Vermont", "state_code": "VT", "state_fp": "50"},
    {"state_name": "Virginia", "state_code": "VA", "state_fp": "51"},
    {"state_name": "Washington", "state_code": "WA", "state_fp": "53"},
    {"state_name": "West Virginia", "state_code": "WV", "state_fp": "54"},
    {"state_name": "Wisconsin", "state_code": "WI", "state_fp": "55"},
    {"state_name": "Wyoming", "state_code": "WY", "state_fp": "56"}
]

